name: Build And Test
description: "Builds the binaries and runs the tests"

inputs:
  numcpp_no_use_boost:
    description: “NUMCPP_NO_USE_BOOST compiler flag”
    required: true
  shell:
    description: the shell to use
    required: true
  boost_root:
    description: the root of the boost installation
    required: true
  conda_bin_dir:
    description: the bin dir for the conda installation
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure CMake
      shell: ${{inputs.shell}}
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=${{inputs.boost_root}} -DNUMCPP_NO_USE_BOOST=${{inputs.numcpp_no_use_boost}} -DBUILD_TESTS=ON -DBUILD_MULTIPLE_TEST=ON -DBUILD_EXAMPLE_README=ON -DBUILD_EXAMPLE_GAUSS_NEWTON_NLLS=ON

    - name: Build
      shell: ${{inputs.shell}}
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Test
      shell: ${{inputs.shell}}
      working-directory: ${{github.workspace}}/test/pytest
      run: ${{conda_bin_dir}}/pytest
