nc::NdArray
typedef const dtype* nc::NdArray< dtype >::const_iterator
typedef dtype* nc::NdArray< dtype >::iterator
dtype* nc::NdArray< dtype >::array_
Endian nc::NdArray< dtype >::endianess_
bool nc::NdArray< dtype >::ownsPtr_
Shape nc::NdArray< dtype >::shape_
uint32 nc::NdArray< dtype >::size_
void nc::NdArray< dtype >::deleteArray() noexcept
Deletes the internal array
void nc::NdArray< dtype >::newArray(const Shape &inShape) noexcept
Creates a new internal array inShape
nc::NdArray< dtype >::NdArray()=default
Defualt Constructor, not very usefull...
Referenced by nc::NdArray< bool >::newbyteorder.
nc::NdArray< dtype >::NdArray(uint32 inSquareSize) noexcept
Constructor inSquareSize square number of rows and columns
nc::NdArray< dtype >::NdArray(uint32 inNumRows, uint32 inNumCols) noexcept
Constructor inNumRows inNumCols
nc::NdArray< dtype >::NdArray(const Shape &inShape) noexcept
Constructor inShape
nc::NdArray< dtype >::NdArray(const std::initializer_list< dtype > &inList) noexcept
Constructor inList
nc::NdArray< dtype >::NdArray(const std::initializer_list< std::initializer_list< dtype > > &inList)
Constructor inList 2D initializer list
nc::NdArray< dtype >::NdArray(const std::vector< dtype > &inVector) noexcept
Constructor inVector
nc::NdArray< dtype >::NdArray(const std::deque< dtype > &inDeque) noexcept
Constructor inDeque
nc::NdArray< dtype >::NdArray(const std::set< dtype > &inSet) noexcept
Constructor inSet
nc::NdArray< dtype >::NdArray(const_iterator inFirst, const_iterator inLast) noexcept
Constructor inFirst inLast
nc::NdArray< dtype >::NdArray(dtype *inPtr, uint32 numRows, uint32 numCols, bool takeOwnership=false) noexcept
Constructor. Operates as a shell around an already existing array of data. inPtr dtype* to beginning of the array numRows the number of rows in the array numCols the nubmer of column in the array takeOwnership whether or not to take ownership of the data and call delete[] in the destructor.
nc::NdArray< dtype >::NdArray(dtype *inPtr, uint32 inNumBytes) noexcept
Constructor. Copies the contents of the buffer into the array. inPtr dtype* to beginning of buffer inNumBytes number of bytes
nc::NdArray< dtype >::NdArray(const NdArray< dtype > &inOtherArray) noexcept
Copy Constructor inOtherArray
nc::NdArray< dtype >::NdArray(NdArray< dtype > &&inOtherArray) noexcept
Move Constructor inOtherArray
nc::NdArray< dtype >::~NdArray()
Destructor
NdArray<bool> nc::NdArray< dtype >::all(Axis inAxis=Axis::NONE) const noexcept
Returns True if all elements evaluate to True or non zeroNumpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.all.html inAxis (Optional, default NONE) NdArray
Referenced by nc::all.
NdArray<bool> nc::NdArray< dtype >::any(Axis inAxis=Axis::NONE) const noexcept
Returns True if any elements evaluate to True or non zeroNumpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.any.html inAxis (Optional, default NONE) NdArray
Referenced by nc::any.
NdArray<uint32> nc::NdArray< dtype >::argmax(Axis inAxis=Axis::NONE) const noexcept
Return indices of the maximum values along the given axis. Only the first index is returned.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.argmax.html inAxis (Optional, default NONE) NdArray
NdArray<uint32> nc::NdArray< dtype >::argmin(Axis inAxis=Axis::NONE) const noexcept
Return indices of the minimum values along the given axis. Only the first index is returned.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.argmin.html inAxis (Optional, default NONE) NdArray
NdArray<uint32> nc::NdArray< dtype >::argsort(Axis inAxis=Axis::NONE) const noexcept
Returns the indices that would sort this array.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.argsort.html inAxis (Optional, default NONE) NdArray
NdArray<dtypeOut> nc::NdArray< dtype >::astype() const noexcept
Returns a copy of the array, cast to a specified type.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.astype.htmlNdArray
dtype& nc::NdArray< dtype >::at(int32 inIndex)
1D access method with bounds checking inIndex value
Referenced by nc::NdArray< bool >::operator[], nc::NdArray< bool >::operator(), nc::NdArray< bool >::put.
const dtype& nc::NdArray< dtype >::at(int32 inIndex) const
const 1D access method with bounds checking inIndex value
dtype& nc::NdArray< dtype >::at(int32 inRowIndex, int32 inColIndex)
2D access method with bounds checking inRowIndex inColIndex value
const dtype& nc::NdArray< dtype >::at(int32 inRowIndex, int32 inColIndex) const
const 2D access method with bounds checking inRowIndex inColIndex value
NdArray<dtype> nc::NdArray< dtype >::at(const Slice &inSlice) const
const 1D access method with bounds checking inSlice Ndarray
NdArray<dtype> nc::NdArray< dtype >::at(const Slice &inRowSlice, const Slice &inColSlice) const
const 2D access method with bounds checking inRowSlice inColSlice Ndarray
NdArray<dtype> nc::NdArray< dtype >::at(const Slice &inRowSlice, int32 inColIndex) const
const 2D access method with bounds checking inRowSlice inColIndex Ndarray
NdArray<dtype> nc::NdArray< dtype >::at(int32 inRowIndex, const Slice &inColSlice) const
const 2D access method with bounds checking inRowIndex inColSlice Ndarray
dtype nc::NdArray< dtype >::back() const noexcept
Returns the last element of the flattened array.dtype
Referenced by nc::filter::nearestBoundary1d.
iterator nc::NdArray< dtype >::begin() noexcept
iterator to the beginning of the flattened array None iterator
Referenced by nc::applyFunction, nc::append, nc::average, nc::concatenate, nc::diff, nc::flip, nc::gradient, nc::nanargmax, nc::nanargmin, nc::nancumprod, nc::nancumsum, nc::nanmax, nc::nanmin, nc::nanprod, nc::nansum, nc::percentile, nc::roll, nc::trim_zeros, nc::NdArray< bool >::NdArray, nc::NdArray< bool >::operator=, nc::NdArray< bool >::astype, nc::NdArray< bool >::clip, nc::NdArray< bool >::fill, nc::NdArray< bool >::flatten, nc::NdArray< bool >::median, nc::NdArray< bool >::newbyteorder, nc::NdArray< bool >::partition, nc::NdArray< bool >::resizeSlow, nc::NdArray< bool >::sort, nc::NdArray< bool >::var, nc::NdArray< bool >::operator&&, nc::NdArray< bool >::operator||, nc::NdArray< bool >::operator~, nc::NdArray< bool >::operator!, nc::NdArray< bool >::operator==, nc::NdArray< bool >::operator!=, nc::NdArray< bool >::operator<, nc::NdArray< bool >::operator>, nc::NdArray< bool >::operator<=, nc::NdArray< bool >::operator>=, nc::nc2pybind, nc::Random< dtype >::bernoulli, nc::Random< dtype >::beta, nc::Random< dtype >::binomial, nc::Random< dtype >::chiSquare, nc::Random< dtype >::cauchy, nc::Random< dtype >::discrete, nc::Random< dtype >::exponential, nc::Random< dtype >::extremeValue, nc::Random< dtype >::f, nc::Random< dtype >::gamma, nc::Random< dtype >::geometric, nc::Random< dtype >::laplace, nc::Random< dtype >::lognormal, nc::Random< dtype >::negativeBinomial, nc::Random< dtype >::nonCentralChiSquared, nc::Random< dtype >::normal, nc::Random< dtype >::permutation, nc::Random< dtype >::poisson, nc::Random< dtype >::rand, nc::Random< dtype >::randFloat, nc::Random< dtype >::randInt, nc::Random< dtype >::randN, nc::Random< dtype >::studentT, nc::Random< dtype >::weibull.
iterator nc::NdArray< dtype >::begin(uint32 inRow)
iterator to the beginning of the input row inRow iterator
const_iterator nc::NdArray< dtype >::begin() const noexcept
const iterator to the beginning of the flattened array None const_iterator
const_iterator nc::NdArray< dtype >::begin(uint32 inRow) const
const iterator to the beginning of the input row inRow const_iterator
void nc::NdArray< dtype >::byteswap() noexcept
Swap the bytes of the array elements in placeNumpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.byteswap.htmlNdArray
Referenced by nc::byteswap.
const_iterator nc::NdArray< dtype >::cbegin() const noexcept
const iterator to the beginning of the flattened arrayconst_iterator
Referenced by nc::append, nc::arccos, nc::arccosh, nc::arcsin, nc::arcsinh, nc::arctan2, nc::average, nc::bincount, nc::copySign, nc::count_nonzero, nc::diff, nc::fmax, nc::fmin, nc::fmod, nc::gradient, nc::hypot, nc::intersect1d, nc::isclose, nc::ldexp, nc::logical_and, nc::logical_or, nc::logical_xor, nc::maximum, nc::minimum, nc::nanmean, nc::nanpercentile, nc::percentile, nc::power, nc::powerf, nc::remainder, nc::setdiff1d, nc::trim_zeros, nc::union1d, nc::NdArray< bool >::begin, nc::NdArray< bool >::all, nc::NdArray< bool >::any, nc::NdArray< bool >::argmax, nc::NdArray< bool >::argmin, nc::NdArray< bool >::astype, nc::NdArray< bool >::clip, nc::NdArray< bool >::contains, nc::NdArray< bool >::dot, nc::NdArray< bool >::flatten, nc::NdArray< bool >::front, nc::NdArray< bool >::max, nc::NdArray< bool >::min, nc::NdArray< bool >::mean, nc::NdArray< bool >::newbyteorder, nc::NdArray< bool >::norm, nc::NdArray< bool >::prod, nc::NdArray< bool >::ptp, nc::NdArray< bool >::rms, nc::NdArray< bool >::row, nc::NdArray< bool >::stdev, nc::NdArray< bool >::sum, nc::NdArray< bool >::operator+=, nc::NdArray< bool >::operator-=, nc::NdArray< bool >::operator*=, nc::NdArray< bool >::operator/=, nc::NdArray< bool >::operator%=, nc::NdArray< bool >::operator|=, nc::NdArray< bool >::operator&=, nc::NdArray< bool >::operator^=, nc::NdArray< bool >::operator&&, nc::NdArray< bool >::operator||, nc::NdArray< bool >::operator==, nc::NdArray< bool >::operator!=, nc::NdArray< bool >::operator>, nc::NdArray< bool >::operator>=, nc::Random< dtype >::discrete.
const_iterator nc::NdArray< dtype >::cbegin(uint32 inRow) const
const iterator to the beginning of the input row inRow const_iterator
const_iterator nc::NdArray< dtype >::cend() const noexcept
const iterator to 1 past the end of the flattened arrayconst_iterator
Referenced by nc::append, nc::arccos, nc::arccosh, nc::arcsin, nc::arcsinh, nc::arctan2, nc::average, nc::bincount, nc::copySign, nc::count_nonzero, nc::diff, nc::fmax, nc::fmin, nc::fmod, nc::gradient, nc::hypot, nc::intersect1d, nc::isclose, nc::ldexp, nc::logical_and, nc::logical_or, nc::logical_xor, nc::maximum, nc::minimum, nc::nanmean, nc::nanpercentile, nc::percentile, nc::power, nc::powerf, nc::remainder, nc::setdiff1d, nc::union1d, nc::NdArray< bool >::end, nc::NdArray< bool >::all, nc::NdArray< bool >::any, nc::NdArray< bool >::argmax, nc::NdArray< bool >::argmin, nc::NdArray< bool >::astype, nc::NdArray< bool >::back, nc::NdArray< bool >::clip, nc::NdArray< bool >::contains, nc::NdArray< bool >::dot, nc::NdArray< bool >::flatten, nc::NdArray< bool >::max, nc::NdArray< bool >::min, nc::NdArray< bool >::mean, nc::NdArray< bool >::newbyteorder, nc::NdArray< bool >::norm, nc::NdArray< bool >::prod, nc::NdArray< bool >::ptp, nc::NdArray< bool >::rms, nc::NdArray< bool >::row, nc::NdArray< bool >::stdev, nc::NdArray< bool >::sum, nc::Random< dtype >::discrete.
const_iterator nc::NdArray< dtype >::cend(uint32 inRow) const
const iterator to 1 past the end of the input row inRow const_iterator
NdArray<dtype> nc::NdArray< dtype >::clip(dtype inMin, dtype inMax) const noexcept
Returns an array whose values are limited to [min, max].Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.clip.html inMin min value to clip to inMax max value to clip to clipped value
Referenced by nc::bincount.
NdArray<dtype> nc::NdArray< dtype >::column(uint32 inColumn)
Returns the full column of the arrayShape
NdArray<bool> nc::NdArray< dtype >::contains(dtype inValue, Axis inAxis=Axis::NONE) const noexcept
returns whether or not a value is included the array inValue inAxis (Optional, default NONE) bool
Referenced by nc::contains, nc::deleteIndices.
NdArray<dtype> nc::NdArray< dtype >::copy() const noexcept
Return a copy of the arrayNumpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.copy.htmlNdArray
Referenced by nc::negative.
const Slice nc::NdArray< dtype >::cSlice(int32 inStartIdx=0, uint32 inStepSize=1) const noexcept
Returns a Slice object for slicing a row to the end of array. inStartIdx (default 0) inStepSize (default 1) Slice
NdArray<dtype> nc::NdArray< dtype >::cumprod(Axis inAxis=Axis::NONE) const noexcept
Return the cumulative product of the elements along the given axis.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.cumprod.html inAxis (Optional, default NONE) NdArray
NdArray<dtype> nc::NdArray< dtype >::cumsum(Axis inAxis=Axis::NONE) const noexcept
Return the cumulative sum of the elements along the given axis.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.cumsum.html inAxis (Optional, default NONE) NdArray
dtype* nc::NdArray< dtype >::data() const noexcept
Returns the raw pointer to the underlying data dtype*
Referenced by nc::nc2pybind.
dtype* nc::NdArray< dtype >::dataRelease() const noexcept
Releases the internal data pointer so that the destructor will not call delete on it, and returns the raw pointer to the underlying data. dtype*
Referenced by nc::nc2pybind.
NdArray<dtype> nc::NdArray< dtype >::diagonal(int32 inOffset=0, Axis inAxis=Axis::ROW) const noexcept
Return specified diagonals.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.diagonal.html inOffset Offset of the diagonal from the main diagonal. Can be both positive and negative. Defaults to 0. inAxis (Optional, default ROW) axis the offset is applied to NdArray
NdArray<dtype> nc::NdArray< dtype >::dot(const NdArray< dtype > &inOtherArray) const
Dot product of two arrays.For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.dot.html inOtherArray dot product
Referenced by nc::dot, nc::matmul, nc::rotations::Quaternion::angularVelocity, nc::rotations::Quaternion::operator*.
void nc::NdArray< dtype >::dump(const std::string &inFilename) const
Dump a binary file of the array to the specified file. The array can be read back with or NC::load.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.dump.html inFilename
Referenced by nc::dump.
iterator nc::NdArray< dtype >::end() noexcept
iterator to 1 past the end of the flattened array iterator
Referenced by nc::applyFunction, nc::average, nc::flip, nc::nanargmax, nc::nanargmin, nc::nancumprod, nc::nancumsum, nc::nanmax, nc::nanmin, nc::nanprod, nc::nansum, nc::percentile, nc::roll, nc::NdArray< bool >::operator=, nc::NdArray< bool >::fill, nc::NdArray< bool >::median, nc::NdArray< bool >::newbyteorder, nc::NdArray< bool >::partition, nc::NdArray< bool >::resizeSlow, nc::NdArray< bool >::sort, nc::NdArray< bool >::var, nc::Random< dtype >::bernoulli, nc::Random< dtype >::beta, nc::Random< dtype >::binomial, nc::Random< dtype >::chiSquare, nc::Random< dtype >::cauchy, nc::Random< dtype >::discrete, nc::Random< dtype >::exponential, nc::Random< dtype >::extremeValue, nc::Random< dtype >::f, nc::Random< dtype >::gamma, nc::Random< dtype >::geometric, nc::Random< dtype >::laplace, nc::Random< dtype >::lognormal, nc::Random< dtype >::negativeBinomial, nc::Random< dtype >::nonCentralChiSquared, nc::Random< dtype >::normal, nc::Random< dtype >::permutation, nc::Random< dtype >::poisson, nc::Random< dtype >::rand, nc::Random< dtype >::randFloat, nc::Random< dtype >::randInt, nc::Random< dtype >::randN, nc::Random< dtype >::studentT, nc::Random< dtype >::weibull.
iterator nc::NdArray< dtype >::end(uint32 inRow)
iterator to the 1 past end of the row inRow iterator
const_iterator nc::NdArray< dtype >::end() const noexcept
const iterator to 1 past the end of the flattened array const_iterator
const_iterator nc::NdArray< dtype >::end(uint32 inRow) const
const iterator to the 1 past end of the row inRow const_iterator
Endian nc::NdArray< dtype >::endianess() const noexcept
Return the NdArrays endianessEndian
void nc::NdArray< dtype >::fill(dtype inFillValue) noexcept
Fill the array with a scalar value.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.fill.html inFillValue None
Referenced by nc::full, nc::pad, nc::NdArray< bool >::nans, nc::NdArray< bool >::ones.
NdArray<dtype> nc::NdArray< dtype >::flatten() const noexcept
Return a copy of the array collapsed into one dimension.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.flatten.htmlNdArray
Referenced by nc::coordinates::Coordinate::radianSeperation, nc::filter::convolve, nc::filter::convolve1d, nc::cross.
dtype nc::NdArray< dtype >::front() const noexcept
Returns the first element of the flattened array.dtype
Referenced by nc::filter::nearestBoundary1d, nc::linalg::SVD::SVD, nc::linalg::SVD::solve, nc::linalg::det, nc::linalg::lstsq, nc::NdArray< bool >::cumprod, nc::NdArray< bool >::cumsum.
NdArray<dtype> nc::NdArray< dtype >::getByIndices(const NdArray< uint32 > &inIndices) const
Returns a new flat array with the givin flat input indices. inIndices values
NdArray<dtype> nc::NdArray< dtype >::getByMask(const NdArray< bool > &inMask) const
Takes in a boolean mask the same size as the array and returns a flattened array with the values cooresponding to the input mask. inMask values
bool nc::NdArray< dtype >::isempty() const noexcept
Return if the NdArray is empty. ie the default construtor was used.boolean
dtype nc::NdArray< dtype >::item() const
Copy an element of an array to a standard C++ scalar and return it.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.item.htmlarray element
Referenced by nc::filter::gaussianFilter, nc::filter::gaussianFilter1d, nc::filter::uniformFilter, nc::filter::uniformFilter1d, nc::allclose, nc::deleteIndices, nc::nanpercentile, nc::nanstdev, nc::NdArray< bool >::stdev, nc::rotations::Quaternion::angleAxisRotation.
NdArray<dtype> nc::NdArray< dtype >::max(Axis inAxis=Axis::NONE) const noexcept
Return the maximum along a given axis.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.max.html inAxis (Optional, default NONE) NdArray
Referenced by nc::filter::maximumFilter, nc::filter::maximumFilter1d, nc::imageProcessing::generateThreshold, nc::bincount, nc::deleteIndices, nc::histogram, nc::interp, nc::NdArray< bool >::operator[].
NdArray<double> nc::NdArray< dtype >::mean(Axis inAxis=Axis::NONE) const noexcept
Return the mean along a given axis.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.mean.html inAxis (Optional, default NONE) NdArray
Referenced by nc::filter::uniformFilter, nc::filter::uniformFilter1d, nc::average, nc::mean, nc::NdArray< bool >::stdev.
NdArray<dtype> nc::NdArray< dtype >::median(Axis inAxis=Axis::NONE) const noexcept
Return the median along a given axis. Does NOT average if array has even number of elements! inAxis (Optional, default NONE) NdArray
Referenced by nc::filter::medianFilter, nc::filter::medianFilter1d.
NdArray<dtype> nc::NdArray< dtype >::min(Axis inAxis=Axis::NONE) const noexcept
Return the minimum along a given axis.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.min.html inAxis (Optional, default NONE) NdArray
Referenced by nc::filter::minimumFilter, nc::filter::minumumFilter1d, nc::imageProcessing::generateThreshold, nc::histogram, nc::interp.
void nc::NdArray< dtype >::nans() noexcept
Fills the array with nans; only really works with. Only really works for dtype = float/double
Referenced by nc::nans_like.
uint64 nc::NdArray< dtype >::nbytes() const noexcept
Returns the number of bytes held by the arrayNumpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.nbytes.htmlnumber of bytes
NdArray<dtype> nc::NdArray< dtype >::newbyteorder(Endian inEndianess) const noexcept
Return the array with the same data viewed with a different byte order. only works for integer types, floating point types will not compile and you will be confused as to why...Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.newbyteorder.html inEndianess NdArray
Referenced by nc::newbyteorder, nc::NdArray< bool >::byteswap.
NdArray<uint32> nc::NdArray< dtype >::nonzero() const noexcept
Return the indices of the flattened array of the elements that are non-zero.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.nonzero.htmlNdArray
Referenced by nc::find, nc::NdArray< bool >::operator[], nc::NdArray< bool >::putMask.
NdArray<double> nc::NdArray< dtype >::norm(Axis inAxis=Axis::NONE) const noexcept
Returns the norm of the arrayNumpy Reference: http://www.numpy.org/devdocs/reference/generated/numpy.linalg.norm.html?highlight=norm#numpy.linalg.norm inAxis (Optional, default NONE) norm
Referenced by nc::norm, nc::rotations::Quaternion::angleAxisRotation.
void nc::NdArray< dtype >::ones() noexcept
Fills the array with ones
Referenced by nc::ones_like, nc::triu.
NdArray<dtype> nc::NdArray< dtype >::operator&(const NdArray< dtype > &inOtherArray) const
Takes the bitwise and of the elements of two arrays inOtherArray NdArray
NdArray<dtype> nc::NdArray< dtype >::operator&(dtype inScalar) const noexcept
Takes the bitwise and of the array and the scalar inScalar NdArray
NdArray<dtype> nc::NdArray< dtype >::operator&&(const NdArray< dtype > &inOtherArray) const
Takes the and of the elements of two arrays inOtherArray None
NdArray<dtype> nc::NdArray< dtype >::operator&&(dtype inScalar) const noexcept
Takes the and of the array and the scalar inScalar NdArray
NdArray<dtype>& nc::NdArray< dtype >::operator&=(const NdArray< dtype > &inOtherArray)
Takes the bitwise and of the elements of two arrays inOtherArray NdArray
NdArray<dtype>& nc::NdArray< dtype >::operator&=(dtype inScalar) noexcept
Takes the bitwise and of the array and the scalar inScalar NdArray
NdArray<bool> nc::NdArray< dtype >::operator!() const noexcept
Takes the not of the arrayNdArray
NdArray<bool> nc::NdArray< dtype >::operator!=(dtype inValue) const noexcept
Returns an array of booleans of element wise comparison of two arrays inValue NdArray
NdArray<bool> nc::NdArray< dtype >::operator!=(const NdArray< dtype > &inOtherArray) const
Returns an array of booleans of element wise comparison of two arrays inOtherArray NdArray
NdArray<dtype> nc::NdArray< dtype >::operator%(const NdArray< dtype > &inOtherArray) const
Takes the modulus of the elements of two arrays inOtherArray NdArray
NdArray<dtype> nc::NdArray< dtype >::operator%(dtype inScalar) const noexcept
Modulus of the array and the scalar inScalar NdArray
NdArray<dtype>& nc::NdArray< dtype >::operator%=(const NdArray< dtype > &inOtherArray)
Takes the modulus of the elements of two arrays inOtherArray NdArray
NdArray<dtype>& nc::NdArray< dtype >::operator%=(dtype inScalar)
Modulus of the array and the scalar inScalar NdArray
dtype& nc::NdArray< dtype >::operator()(int32 inRowIndex, int32 inColIndex) noexcept
2D access operator with no bounds checking inRowIndex inColIndex value
Referenced by nc::NdArray< bool >::at, nc::NdArray< bool >::argsort, nc::NdArray< bool >::column, nc::NdArray< bool >::cumprod, nc::NdArray< bool >::cumsum, nc::NdArray< bool >::resizeSlow.
const dtype& nc::NdArray< dtype >::operator()(int32 inRowIndex, int32 inColIndex) const noexcept
const 2D access operator with no bounds checking inRowIndex inColIndex value
NdArray<dtype> nc::NdArray< dtype >::operator()(const Slice &inRowSlice, const Slice &inColSlice) const
2D Slicing access operator with bounds checking. returned array is of the range [start, stop). inRowSlice inColSlice NdArray
NdArray<dtype> nc::NdArray< dtype >::operator()(const Slice &inRowSlice, int32 inColIndex) const
2D Slicing access operator with bounds checking. returned array is of the range [start, stop). inRowSlice inColIndex NdArray
NdArray<dtype> nc::NdArray< dtype >::operator()(int32 inRowIndex, const Slice &inColSlice) const
2D Slicing access operator with bounds checking. returned array is of the range [start, stop). inRowIndex inColSlice NdArray
NdArray<dtype> nc::NdArray< dtype >::operator*(const NdArray< dtype > &inOtherArray) const
Multiplies the elements of two arrays inOtherArray NdArray
NdArray<dtype> nc::NdArray< dtype >::operator*(dtype inScalar) const noexcept
Muliplies the scalar to the array inScalar NdArray
NdArray<dtype>& nc::NdArray< dtype >::operator*=(const NdArray< dtype > &inOtherArray)
Multiplies the elements of two arrays inOtherArray NdArray
NdArray<dtype>& nc::NdArray< dtype >::operator*=(dtype inScalar) noexcept
Muliplies the scalar to the array inScalar NdArray
NdArray<dtype> nc::NdArray< dtype >::operator+(const NdArray< dtype > &inOtherArray) const
Adds the elements of two arrays inOtherArray NdArray
NdArray<dtype> nc::NdArray< dtype >::operator+(dtype inScalar) const noexcept
Adds the scalar to the array inScalar NdArray
NdArray<dtype>& nc::NdArray< dtype >::operator++() noexcept
prefix incraments the elements of an arrayNdArray
NdArray<dtype> nc::NdArray< dtype >::operator++(int) noexcept
postfix increments the elements of an arrayNdArray
NdArray<dtype>& nc::NdArray< dtype >::operator+=(const NdArray< dtype > &inOtherArray)
Adds the elements of two arrays inOtherArray NdArray
NdArray<dtype>& nc::NdArray< dtype >::operator+=(dtype inScalar) noexcept
Adds the scalar to the array inScalar NdArray
NdArray<dtype> nc::NdArray< dtype >::operator-(const NdArray< dtype > &inOtherArray) const
Subtracts the elements of two arrays inOtherArray NdArray
NdArray<dtype> nc::NdArray< dtype >::operator-(dtype inScalar) const noexcept
Subtracts the scalar from the array inScalar NdArray
NdArray<dtype>& nc::NdArray< dtype >::operator--() noexcept
prefix decrements the elements of an arrayNdArray
NdArray<dtype> nc::NdArray< dtype >::operator--(int) noexcept
postfix decrements the elements of an arrayNdArray
NdArray<dtype>& nc::NdArray< dtype >::operator-=(const NdArray< dtype > &inOtherArray)
Subtracts the elements of two arrays inOtherArray NdArray
NdArray<dtype>& nc::NdArray< dtype >::operator-=(dtype inScalar) noexcept
Subtracts the scalar from the array inScalar NdArray
NdArray<dtype> nc::NdArray< dtype >::operator/(const NdArray< dtype > &inOtherArray) const
Divides the elements of two arrays inOtherArray NdArray
NdArray<dtype> nc::NdArray< dtype >::operator/(dtype inScalar) const noexcept
Divides the array by the scalar inScalar NdArray
NdArray<dtype>& nc::NdArray< dtype >::operator/=(const NdArray< dtype > &inOtherArray)
Divides the elements of two arrays inOtherArray NdArray
NdArray<dtype>& nc::NdArray< dtype >::operator/=(dtype inScalar) noexcept
Divides the array by the scalar inScalar NdArray
NdArray<bool> nc::NdArray< dtype >::operator<(const NdArray< dtype > &inOtherArray) const
Returns an array of booleans of element wise comparison of two arrays inOtherArray NdArray
NdArray<bool> nc::NdArray< dtype >::operator<(dtype inValue) const noexcept
Returns an array of booleans of element wise comparison the array and a scalar inValue NdArray
NdArray<bool> nc::NdArray< dtype >::operator<=(const NdArray< dtype > &inOtherArray) const
Returns an array of booleans of element wise comparison of two arrays inOtherArray NdArray
NdArray<bool> nc::NdArray< dtype >::operator<=(dtype inValue) const noexcept
Returns an array of booleans of element wise comparison the array and a scalar inValue NdArray
NdArray<dtype>& nc::NdArray< dtype >::operator=(const NdArray< dtype > &inOtherArray) noexcept
Assignment operator, performs a deep copy inOtherArray NdArray<dtype>
NdArray<dtype>& nc::NdArray< dtype >::operator=(dtype inValue) noexcept
Assignment operator, sets the entire array to a single scalar value. inValue NdArray<dtype>
NdArray<dtype>& nc::NdArray< dtype >::operator=(NdArray< dtype > &&inOtherArray) noexcept
Move operator, performs a deep move inOtherArray NdArray<dtype>
NdArray<bool> nc::NdArray< dtype >::operator==(dtype inValue) const noexcept
Returns an array of booleans of element wise comparison of two arrays inValue NdArray
NdArray<bool> nc::NdArray< dtype >::operator==(const NdArray< dtype > &inOtherArray) const
Returns an array of booleans of element wise comparison of two arrays inOtherArray NdArray
NdArray<bool> nc::NdArray< dtype >::operator>(dtype inValue) const noexcept
Returns an array of booleans of element wise comparison the array and a scalar inValue NdArray
NdArray<bool> nc::NdArray< dtype >::operator>(const NdArray< dtype > &inOtherArray) const
Returns an array of booleans of element wise comparison of two arrays inOtherArray NdArray
NdArray<bool> nc::NdArray< dtype >::operator>=(dtype inValue) const noexcept
Returns an array of booleans of element wise comparison the array and a scalar inValue NdArray
NdArray<bool> nc::NdArray< dtype >::operator>=(const NdArray< dtype > &inOtherArray) const
Returns an array of booleans of element wise comparison of two arrays inOtherArray NdArray
dtype& nc::NdArray< dtype >::operator[](int32 inIndex) noexcept
1D access operator with no bounds checking inIndex value
Referenced by nc::NdArray< bool >::operator[], nc::NdArray< bool >::at, nc::NdArray< bool >::getByIndices, nc::NdArray< bool >::getByMask.
const dtype& nc::NdArray< dtype >::operator[](int32 inIndex) const noexcept
const 1D access operator with no bounds checking inIndex value
NdArray<dtype> nc::NdArray< dtype >::operator[](const Slice &inSlice) const
1D Slicing access operator with bounds checking. returned array is of the range [start, stop). inSlice NdArray
NdArray<dtype> nc::NdArray< dtype >::operator[](const NdArray< bool > &inMask) const
Returns the values from the input mask inMask NdArray
NdArray<dtype> nc::NdArray< dtype >::operator[](const NdArray< uint32 > &inIndices) const
Returns the values from the input indices inIndices NdArray
NdArray<dtype> nc::NdArray< dtype >::operator^(const NdArray< dtype > &inOtherArray) const
Takes the bitwise xor of the elements of two arrays inOtherArray None
NdArray<dtype> nc::NdArray< dtype >::operator^(dtype inScalar) const noexcept
Takes the bitwise xor of the array and the scalar inScalar NdArray
NdArray<dtype>& nc::NdArray< dtype >::operator^=(const NdArray< dtype > &inOtherArray)
Takes the bitwise xor of the elements of two arrays inOtherArray None
NdArray<dtype>& nc::NdArray< dtype >::operator^=(dtype inScalar) noexcept
Takes the bitwise xor of the array and the scalar inScalar NdArray
NdArray<dtype> nc::NdArray< dtype >::operator|(const NdArray< dtype > &inOtherArray) const
Takes the bitwise or of the elements of two arrays inOtherArray NdArray
NdArray<dtype> nc::NdArray< dtype >::operator|(dtype inScalar) const noexcept
Takes the bitwise or of the array and the scalar inScalar NdArray
NdArray<dtype>& nc::NdArray< dtype >::operator|=(const NdArray< dtype > &inOtherArray)
Takes the bitwise or of the elements of two arrays inOtherArray NdArray
NdArray<dtype>& nc::NdArray< dtype >::operator|=(dtype inScalar) noexcept
Takes the bitwise or of the array and the scalar inScalar NdArray
NdArray<dtype> nc::NdArray< dtype >::operator||(const NdArray< dtype > &inOtherArray) const
Takes the or of the elements of two arrays inOtherArray None
NdArray<dtype> nc::NdArray< dtype >::operator||(dtype inScalar) const noexcept
Takes the or of the array and the scalar inScalar NdArray
NdArray<dtype> nc::NdArray< dtype >::operator~() const noexcept
Takes the bitwise not of the arrayNdArray
bool nc::NdArray< dtype >::ownsInternalData() noexcept
Returns whether or not the array object owns the underlying databool
Referenced by nc::nc2pybind.
void nc::NdArray< dtype >::partition(uint32 inKth, Axis inAxis=Axis::NONE)
Rearranges the elements in the array in such a way that value of the element in kth position is in the position it would be in a sorted array. All elements smaller than the kth element are moved before this element and all equal or greater are moved behind it. The ordering of the elements in the two partitions is undefined.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.partition.html inKth kth element inAxis (Optional, default NONE) None
Referenced by nc::partition.
void nc::NdArray< dtype >::print() const noexcept
Prints the array to the console.
NdArray<dtype> nc::NdArray< dtype >::prod(Axis inAxis=Axis::NONE) const noexcept
Return the product of the array elements over the given axisNumpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.prod.html inAxis (Optional, default NONE) NdArray
NdArray<dtype> nc::NdArray< dtype >::ptp(Axis inAxis=Axis::NONE) const noexcept
Peak to peak (maximum - minimum) value along a given axis.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.ptp.html inAxis (Optional, default NONE) NdArray
NdArray<dtype>& nc::NdArray< dtype >::put(int32 inIndex, dtype inValue)
set the flat index element to the valueNumpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.put.html inIndex inValue
Referenced by nc::filter::fillCorners, nc::filter::reflectBoundary, nc::filter::reflectBoundary1d, nc::filter::constantBoundary, nc::filter::constantBoundary1d, nc::filter::nearestBoundary, nc::filter::nearestBoundary1d, nc::filter::mirrorBoundary, nc::filter::mirrorBoundary1d, nc::filter::wrapBoundary, nc::filter::wrapBoundary1d, nc::cross, nc::pad, nc::put, nc::NdArray< bool >::put, nc::NdArray< bool >::putMask, nc::NdArray< bool >::repeat.
NdArray<dtype>& nc::NdArray< dtype >::put(int32 inRow, int32 inCol, dtype inValue)
set the 2D row/col index element to the valueNumpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.put.html inRow inCol inValue
NdArray<dtype>& nc::NdArray< dtype >::put(const NdArray< uint32 > &inIndices, dtype inValue)
Set a.flat[n] = values for all n in indices.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.put.html inIndices inValue
NdArray<dtype>& nc::NdArray< dtype >::put(const NdArray< uint32 > &inIndices, const NdArray< dtype > &inValues)
Set a.flat[n] = values[n] for all n in indices.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.put.html inIndices inValues
NdArray<dtype>& nc::NdArray< dtype >::put(const Slice &inSlice, dtype inValue)
Set the slice indices to the input value.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.put.html inSlice inValue
NdArray<dtype>& nc::NdArray< dtype >::put(const Slice &inSlice, const NdArray< dtype > &inValues)
Set the slice indices to the input values.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.put.html inSlice inValues
NdArray<dtype>& nc::NdArray< dtype >::put(const Slice &inRowSlice, const Slice &inColSlice, dtype inValue)
Set the slice indices to the input value.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.put.html inRowSlice inColSlice inValue
NdArray<dtype>& nc::NdArray< dtype >::put(const Slice &inRowSlice, int32 inColIndex, dtype inValue)
Set the slice indices to the input value.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.put.html inRowSlice inColIndex inValue
NdArray<dtype>& nc::NdArray< dtype >::put(int32 inRowIndex, const Slice &inColSlice, dtype inValue)
Set the slice indices to the input value.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.put.html inRowIndex inColSlice inValue
NdArray<dtype>& nc::NdArray< dtype >::put(const Slice &inRowSlice, const Slice &inColSlice, const NdArray< dtype > &inValues)
Set the slice indices to the input values.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.put.html inRowSlice inColSlice inValues
NdArray<dtype>& nc::NdArray< dtype >::put(const Slice &inRowSlice, int32 inColIndex, const NdArray< dtype > &inValues)
Set the slice indices to the input values.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.put.html inRowSlice inColIndex inValues
NdArray<dtype>& nc::NdArray< dtype >::put(int32 inRowIndex, const Slice &inColSlice, const NdArray< dtype > &inValues)
Set the slice indices to the input values.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.put.html inRowIndex inColSlice inValues
NdArray<dtype>& nc::NdArray< dtype >::putMask(const NdArray< bool > &inMask, dtype inValue)
Set the mask indices to the input value. inMask inValue
Referenced by nc::putmask.
NdArray<dtype>& nc::NdArray< dtype >::putMask(const NdArray< bool > &inMask, const NdArray< dtype > &inValues)
Set the mask indices to the input values. inMask inValues
NdArray<dtype> nc::NdArray< dtype >::repeat(uint32 inNumRows, uint32 inNumCols) const noexcept
Repeat elements of an array.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.repeat.html inNumRows inNumCols NdArray
Referenced by nc::NdArray< bool >::repeat.
NdArray<dtype> nc::NdArray< dtype >::repeat(const Shape &inRepeatShape) const noexcept
Repeat elements of an array.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.repeat.html inRepeatShape NdArray
void nc::NdArray< dtype >::reshape(uint32 inNumRows, uint32 inNumCols)
Resizes the array to a new shape.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.repeat.html inNumRows inNumCols
Referenced by nc::reshape, nc::NdArray< bool >::reshape.
void nc::NdArray< dtype >::reshape(const Shape &inShape)
Resizes the array to a new shape.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.reshape.html inShape
void nc::NdArray< dtype >::resizeFast(uint32 inNumRows, uint32 inNumCols) noexcept
Change shape and size of array in-place. All previous data of the array is lost.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.resize.html inNumRows inNumCols
Referenced by nc::NdArray< bool >::resizeFast.
void nc::NdArray< dtype >::resizeFast(const Shape &inShape) noexcept
Change shape and size of array in-place. All previous data of the array is lost.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.resize.html inShape
void nc::NdArray< dtype >::resizeSlow(uint32 inNumRows, uint32 inNumCols) noexcept
Return a new array with the specified shape. If new shape is larger than old shape then array will be padded with zeros. If new shape is smaller than the old shape then the data will be discarded.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.resize.html inNumRows inNumCols
Referenced by nc::NdArray< bool >::resizeSlow.
void nc::NdArray< dtype >::resizeSlow(const Shape &inShape) noexcept
Return a new array with the specified shape. If new shape is larger than old shape then array will be padded with zeros. If new shape is smaller than the old shape then the data will be discarded.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.resize.html inShape
NdArray<double> nc::NdArray< dtype >::rms(Axis inAxis=Axis::NONE) const noexcept
Return the root mean square (RMS) along a given axis. inAxis (Optional, default NONE) NdArray
Referenced by nc::rms.
NdArray<dtype> nc::NdArray< dtype >::round(uint8 inNumDecimals=0) const noexcept
Return a with each element rounded to the given number of decimals.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.round.html inNumDecimals (default 0) NdArray
Referenced by nc::around, nc::round.
NdArray<dtype> nc::NdArray< dtype >::row(uint32 inRow)
Returns the full row of the arrayShape
Referenced by nc::NdArray< bool >::NdArray, nc::NdArray< bool >::operator(), nc::NdArray< bool >::all, nc::NdArray< bool >::any, nc::NdArray< bool >::argmax, nc::NdArray< bool >::argmin, nc::NdArray< bool >::argsort, nc::NdArray< bool >::contains, nc::NdArray< bool >::cumprod, nc::NdArray< bool >::cumsum, nc::NdArray< bool >::diagonal, nc::NdArray< bool >::max, nc::NdArray< bool >::min, nc::NdArray< bool >::mean, nc::NdArray< bool >::median, nc::NdArray< bool >::norm, nc::NdArray< bool >::partition, nc::NdArray< bool >::prod, nc::NdArray< bool >::ptp, nc::NdArray< bool >::put, nc::NdArray< bool >::repeat, nc::NdArray< bool >::resizeSlow, nc::NdArray< bool >::rms, nc::NdArray< bool >::sort, nc::NdArray< bool >::stdev.
const Slice nc::NdArray< dtype >::rSlice(int32 inStartIdx=0, uint32 inStepSize=1) const noexcept
Returns a Slice object for slicing a column to the end of the array. inStartIdx (default 0) inStepSize (default 1) Slice
Referenced by nc::NdArray< bool >::column.
Shape nc::NdArray< dtype >::shape() const noexcept
Return the shape of the arrayNumpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.shape.htmlShape
Referenced by nc::DataCube< dtype >::push_back, nc::DataCube< dtype >::push_front, nc::filter::fillCorners, nc::filter::reflectBoundary, nc::filter::constantBoundary, nc::filter::nearestBoundary, nc::filter::mirrorBoundary, nc::filter::wrapBoundary, nc::filter::trimBoundary, nc::filter::convolve, nc::filter::maximumFilter, nc::filter::medianFilter, nc::filter::minimumFilter, nc::filter::percentileFilter, nc::filter::rankFilter, nc::filter::uniformFilter, nc::imageProcessing::ClusterMaker< dtype >::ClusterMaker, nc::imageProcessing::windowExceedances, nc::linalg::det, nc::linalg::inv, nc::linalg::matrix_power, nc::allclose, nc::append, nc::arccos, nc::arccosh, nc::arcsin, nc::arcsinh, nc::arctan2, nc::average, nc::bincount, nc::copySign, nc::count_nonzero, nc::cross, nc::deleteIndices, nc::diff, nc::flip, nc::fmax, nc::fmin, nc::fmod, nc::gradient, nc::hypot, nc::isclose, nc::ldexp, nc::logical_and, nc::logical_or, nc::logical_xor, nc::maximum, nc::minimum, nc::nanmean, nc::nanmedian, nc::nanpercentile, nc::nanstdev, nc::pad, nc::percentile, nc::power, nc::powerf, nc::remainder, nc::trapz, nc::union1d, nc::where, nc::NdArray< bool >::operator[], nc::NdArray< bool >::putMask, nc::NdArray< bool >::sum, nc::nc2pybind, nc::rotations::Quaternion::fromDCM.
uint32 nc::NdArray< dtype >::size() const noexcept
Return the size of the arrayNumpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.size.htmlsize
Referenced by nc::coordinates::Coordinate::Coordinate, nc::coordinates::Coordinate::radianSeperation, nc::filter::reflectBoundary1d, nc::filter::constantBoundary1d, nc::filter::nearestBoundary1d, nc::filter::mirrorBoundary1d, nc::filter::wrapBoundary1d, nc::filter::trimBoundary1d, nc::filter::convolve, nc::filter::convolve1d, nc::filter::maximumFilter1d, nc::filter::medianFilter1d, nc::filter::minumumFilter1d, nc::filter::percentileFilter1d, nc::filter::rankFilter1d, nc::filter::uniformFilter1d, nc::linalg::SVD::solve, nc::linalg::hat, nc::append, nc::average, nc::count_nonzero, nc::cross, nc::deleteIndices, nc::find, nc::gradient, nc::histogram, nc::interp, nc::intersect1d, nc::nanpercentile, nc::percentile, nc::setdiff1d, nc::trapz, nc::trim_zeros, nc::NdArray< bool >::operator[], nc::NdArray< bool >::put, nc::Poly1d< dtype >::Poly1d, nc::Random< dtype >::choice, nc::rotations::Quaternion::Quaternion, nc::rotations::Quaternion::angleAxisRotation, nc::rotations::Quaternion::rotate, nc::rotations::Quaternion::operator*, nc::rotations::DCM< dtype >::angleAxisRotation.
void nc::NdArray< dtype >::sort(Axis inAxis=Axis::NONE) noexcept
Sort an array, in-place.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.sort.html inAxis (Optional, default NONE) size
Referenced by nc::sort.
NdArray<double> nc::NdArray< dtype >::stdev(Axis inAxis=Axis::NONE) const noexcept
Return the std along a given axis.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.std.html inAxis (Optional, default NONE) NdArray
Referenced by nc::stdev.
std::string nc::NdArray< dtype >::str() const noexcept
returns the NdArray as a string representationstring
Referenced by nc::coordinates::Coordinate::str.
NdArray<dtype> nc::NdArray< dtype >::sum(Axis inAxis=Axis::NONE) const noexcept
Return the sum of the array elements over the given axis.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.sum.html inAxis (Optional, default NONE) NdArray
Referenced by nc::filter::gaussianFilter, nc::filter::gaussianFilter1d, nc::NdArray< bool >::mean, nc::NdArray< bool >::stdev.
NdArray<dtype> nc::NdArray< dtype >::swapaxes() const noexcept
Interchange two axes of an array. Equivalent to transpose...Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.swapaxes.htmlNdArray
void nc::NdArray< dtype >::tofile(const std::string &inFilename, const std::string &inSep="") const
Write array to a file as text or binary (default).. The data produced by this method can be recovered using the function fromfile().Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.tofile.html inFilename inSep Separator between array items for text output. If "" (empty), a binary file is written None
Referenced by nc::tofile.
std::vector<dtype> nc::NdArray< dtype >::toStlVector() const noexcept
Write flattened array to an STL vectorstd::vector
dtype nc::NdArray< dtype >::trace(uint32 inOffset=0, Axis inAxis=Axis::ROW) const noexcept
Return the sum along diagonals of the array.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.trace.html inOffset Offset of the diagonal from the main diagonal. Can be both positive and negative. Defaults to 0. inAxis (Optional, default ROW) Axis to offset from value
NdArray<dtype> nc::NdArray< dtype >::transpose() const noexcept
Tranpose the rows and columns of an arrayNumpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.transpose.htmlNdArray
Referenced by nc::linalg::svd, nc::average, nc::count_nonzero, nc::diff, nc::flip, nc::nanmean, nc::nanmedian, nc::nanpercentile, nc::nanstdev, nc::percentile, nc::roll, nc::trapz, nc::NdArray< bool >::all, nc::NdArray< bool >::any, nc::NdArray< bool >::argmax, nc::NdArray< bool >::argmin, nc::NdArray< bool >::argsort, nc::NdArray< bool >::contains, nc::NdArray< bool >::dot, nc::NdArray< bool >::max, nc::NdArray< bool >::min, nc::NdArray< bool >::mean, nc::NdArray< bool >::median, nc::NdArray< bool >::norm, nc::NdArray< bool >::partition, nc::NdArray< bool >::prod, nc::NdArray< bool >::ptp, nc::NdArray< bool >::rms, nc::NdArray< bool >::sort, nc::NdArray< bool >::stdev, nc::rotations::Quaternion::angularVelocity.
NdArray<double> nc::NdArray< dtype >::var(Axis inAxis=Axis::NONE) const noexcept
Returns the variance of the array elements, along given axis.Numpy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ndarray.var.html inAxis (Optional, default NONE) NdArray
Referenced by nc::var.
void nc::NdArray< dtype >::zeros()
Fills the array with zeros
Referenced by nc::bincount, nc::diagflat, nc::eye, nc::identity, nc::tril, nc::zeros_like, nc::NdArray< bool >::resizeFast, nc::rotations::Quaternion::angularVelocity.
NdArray<dtype> operator<<(const NdArray< dtype > &lhs, uint8 inNumBits) noexcept
Bitshifts left the elements of the array lhs inNumBits NdArray
std::ostream& operator<<(std::ostream &inOStream, const NdArray< dtype > &inArray) noexcept
io operator for the NdArray class inOStream inArray std::ostream
NdArray<dtype>& operator<<=(NdArray< dtype > &lhs, uint8 inNumBits) noexcept
Bitshifts left the elements of the array lhs inNumBits NdArray
NdArray<dtype> operator>>(const NdArray< dtype > &lhs, uint8 inNumBits) noexcept
Bitshifts right the elements of the array lhs inNumBits NdArray
NdArray<dtype>& operator>>=(NdArray< dtype > &lhs, uint8 inNumBits) noexcept
Bitshifts right the elements of the array lhs inNumBits NdArray