nc::linalg::SVD
double nc::linalg::SVD::eps_
const uint32 nc::linalg::SVD::m_
const uint32 nc::linalg::SVD::n_
NdArray<double> nc::linalg::SVD::s_
double nc::linalg::SVD::tsh_
NdArray<double> nc::linalg::SVD::u_
NdArray<double> nc::linalg::SVD::v_
nc::linalg::SVD::SVD(const NdArray< double > &inMatrix)
Constructor inMatrix matrix to perform SVD on
References nc::sqrt, nc::NdArray< dtype >::front.
const NdArray<double>& nc::linalg::SVD::s() noexcept
the resultant w matrixs matrix
Referenced by nc::linalg::lstsq, nc::linalg::svd.
NdArray<double> nc::linalg::SVD::solve(const NdArray< double > &inInput, double inThresh=-1.0)
solves the linear least squares problem inInput inThresh (default -1.0) NdArray
References nc::NdArray< dtype >::size, nc::sqrt, nc::NdArray< dtype >::front.
Referenced by nc::linalg::lstsq.
const NdArray<double>& nc::linalg::SVD::u() noexcept
the resultant u matrixu matrix
Referenced by nc::linalg::svd.
const NdArray<double>& nc::linalg::SVD::v() noexcept
the resultant v matrixv matrix
Referenced by nc::linalg::svd.
void nc::linalg::SVD::decompose()
decomposes the input matrix
double nc::linalg::SVD::pythag(double inA, double inB) noexcept
performs pythag of input values inA inB resultant value
void nc::linalg::SVD::reorder()
reorders the input matrix
double nc::linalg::SVD::SIGN(double inA, double inB) noexcept
returns the SIGN of two values inA inB value