nc::rotations::DCM
static NdArray<double> nc::rotations::DCM< dtype >::angleAxisRotation(const NdArray< dtype > &inArray, double inAngle)
returns a direction cosine matrix that rotates about the input axis by the input angle inArray (cartesian vector with x,y,z) inAngle (in radians) NdArray
References nc::NdArray< dtype >::size, nc::rotations::Quaternion::angleAxisRotation, nc::rotations::Quaternion::toDCM.
Referenced by nc::rotations::DCM< dtype >::xRotation, nc::rotations::DCM< dtype >::yRotation, nc::rotations::DCM< dtype >::zRotation.
static bool nc::rotations::DCM< dtype >::isValid(const NdArray< dtype > &inArray) noexcept
returns whether the input array is a direction cosine matrix inArray bool
References nc::Shape::rows, nc::Shape::cols, nc::round.
static NdArray<double> nc::rotations::DCM< dtype >::xRotation(double inAngle)
returns a direction cosine matrix that rotates about the x axis by the input angle inAngle (in radians) NdArray<double>
References nc::rotations::DCM< dtype >::angleAxisRotation.
static NdArray<double> nc::rotations::DCM< dtype >::yRotation(double inAngle)
returns a direction cosine matrix that rotates about the x axis by the input angle inAngle (in radians) NdArray<double>
References nc::rotations::DCM< dtype >::angleAxisRotation.
static NdArray<double> nc::rotations::DCM< dtype >::zRotation(double inAngle)
returns a direction cosine matrix that rotates about the x axis by the input angle inAngle (in radians) NdArray<double>
References nc::rotations::DCM< dtype >::angleAxisRotation.