nc::coordinates::Coordinate
Dec nc::coordinates::Coordinate::dec_
RA nc::coordinates::Coordinate::ra_
double nc::coordinates::Coordinate::x_
double nc::coordinates::Coordinate::y_
double nc::coordinates::Coordinate::z_
void nc::coordinates::Coordinate::cartesianToPolar()
Converts polar coordinates to cartesian coordinates
void nc::coordinates::Coordinate::polarToCartesian() noexcept
Converts polar coordinates to cartesian coordinates
nc::coordinates::Coordinate::Coordinate() noexcept=default
Default Constructor, not super usefull on its own
nc::coordinates::Coordinate::Coordinate(double inRaDegrees, double inDecDegrees)
Constructor inRaDegrees inDecDegrees
nc::coordinates::Coordinate::Coordinate(uint8 inRaHours, uint8 inRaMinutes, double inRaSeconds, Sign inSign, uint8 inDecDegreesWhole, uint8 inDecMinutes, double inDecSeconds) noexcept
Constructor inRaHours inRaMinutes inRaSeconds inSign inDecDegreesWhole inDecMinutes inDecSeconds
nc::coordinates::Coordinate::Coordinate(const RA &inRA, const Dec &inDec) noexcept
Constructor inRA inDec
nc::coordinates::Coordinate::Coordinate(double inX, double inY, double inZ)
Constructor inX inY inZ
nc::coordinates::Coordinate::Coordinate(const NdArray< double > inCartesianVector)
Constructor inCartesianVector
References nc::NdArray< dtype >::size.
const Dec& nc::coordinates::Coordinate::dec() const noexcept
Returns the Dec objectDec
double nc::coordinates::Coordinate::degreeSeperation(const Coordinate &inOtherCoordinate) const
Returns the degree seperation between the two Coordinates inOtherCoordinate degrees
References nc::rad2deg, radianSeperation.
Referenced by nc::coordinates::degreeSeperation.
double nc::coordinates::Coordinate::degreeSeperation(const NdArray< double > &inVector) const
Returns the degree seperation between the Coordinate and the input vector inVector degrees
References nc::rad2deg, radianSeperation.
bool nc::coordinates::Coordinate::operator!=(const Coordinate &inRhs) const noexcept
Not equality operator inRhs bool
bool nc::coordinates::Coordinate::operator==(const Coordinate &inRhs) const noexcept
Equality operator inRhs bool
void nc::coordinates::Coordinate::print() const
Prints the Coordinate object to the console
const RA& nc::coordinates::Coordinate::ra() const noexcept
Returns the RA objectRA
double nc::coordinates::Coordinate::radianSeperation(const Coordinate &inOtherCoordinate) const
Returns the radian seperation between the two Coordinates inOtherCoordinate radians
References nc::dot, xyz.
Referenced by degreeSeperation, nc::coordinates::radianSeperation.
double nc::coordinates::Coordinate::radianSeperation(const NdArray< double > &inVector) const
Returns the radian seperation between the Coordinate and the input vector inVector radians
References nc::NdArray< dtype >::size, nc::dot, xyz, nc::NdArray< dtype >::flatten.
std::string nc::coordinates::Coordinate::str() const
Returns coordinate as a string representationstring
References nc::coordinates::RA::str, nc::coordinates::Dec::str, xyz, nc::NdArray< dtype >::str.
double nc::coordinates::Coordinate::x() const noexcept
Returns the cartesian x valuex
NdArray<double> nc::coordinates::Coordinate::xyz() const
Returns the cartesian xyz triplet as an NdArrayNdArray
Referenced by radianSeperation, str.
double nc::coordinates::Coordinate::y() const noexcept
Returns the cartesian y valuey
double nc::coordinates::Coordinate::z() const noexcept
Returns the cartesian z valuez
std::ostream& operator<<(std::ostream &inStream, const Coordinate &inCoord)
Ostream operator inStream inCoord std::ostream