nc::rotations::Quaternion
double nc::rotations::Quaternion::data_[4][4]
void nc::rotations::Quaternion::normalize() noexcept
renormalizes the quaternion
nc::rotations::Quaternion::Quaternion() noexcept=default
Default Constructor, not super usefull on its own
Referenced by angleAxisRotation, conjugate, identity, fromDCM, nlerp, slerp, operator+, operator-, operator*, operator/.
nc::rotations::Quaternion::Quaternion(double inI, double inJ, double inK, double inS) noexcept
Constructor inI inJ inK inS
References nc::norm, nc::sqrt, nc::utils::sqr.
nc::rotations::Quaternion::Quaternion(const NdArray< double > &inArray)
Constructor inArray (size = 4)
References nc::NdArray< dtype >::size, nc::norm, nc::sqrt, nc::square, nc::sum.
NdArray<double> nc::rotations::Quaternion::angularVelocity(const Quaternion &inQuat2, double inTime) const noexcept
angular velocity vector between the two quaternions. The norm of the array is the magnitude inQuat2 inTime (seperation time) NdArray<double>
References angularVelocity.
Quaternion nc::rotations::Quaternion::conjugate() const noexcept
quaternion conjugateQuaternion
References Quaternion, i, j, k, s.
Referenced by inverse, operator/=.
double nc::rotations::Quaternion::i() const noexcept
returns the i componentdouble
Referenced by angleAxisRotation, conjugate, nlerp, str, toDCM.
Quaternion nc::rotations::Quaternion::inverse() const noexcept
quaternion inverseQuaterion
References conjugate.
double nc::rotations::Quaternion::j() const noexcept
returns the j componentdouble
Referenced by angleAxisRotation, conjugate, nlerp, str, toDCM.
double nc::rotations::Quaternion::k() const noexcept
returns the k componentdouble
Referenced by angleAxisRotation, conjugate, nlerp, str, toDCM.
Quaternion nc::rotations::Quaternion::nlerp(const Quaternion &inQuat2, double inPercent) const
linearly interpolates between the two quaternions inQuat2 inPercent (0, 1) Quaternion
References nlerp.
bool nc::rotations::Quaternion::operator!=(const Quaternion &inRhs) const noexcept
equality operator inRhs bool
Quaternion nc::rotations::Quaternion::operator*(const Quaternion &inRhs) const noexcept
multiplication operator inRhs Quaternion
References Quaternion.
Quaternion nc::rotations::Quaternion::operator*(double inScalar) const noexcept
multiplication operator, only useful for multiplying by negative 1, all others will be renormalized back out inScalar Quaternion
References Quaternion.
NdArray<double> nc::rotations::Quaternion::operator*(const NdArray< dtype > &inVec) const
multiplication operator inVec NdArray<double>
References nc::NdArray< dtype >::size, toDCM, nc::NdArray< dtype >::dot.
Quaternion& nc::rotations::Quaternion::operator*=(const Quaternion &inRhs) noexcept
multiplication assignment operator inRhs Quaternion
Quaternion& nc::rotations::Quaternion::operator*=(double inScalar) noexcept
multiplication operator, only useful for multiplying by negative 1, all others will be renormalized back out inScalar Quaternion
Quaternion nc::rotations::Quaternion::operator+(const Quaternion &inRhs) const noexcept
addition operator inRhs Quaternion
References Quaternion.
Quaternion& nc::rotations::Quaternion::operator+=(const Quaternion &inRhs) noexcept
addition assignment operator inRhs Quaternion
Quaternion nc::rotations::Quaternion::operator-(const Quaternion &inRhs) const noexcept
subtraction operator inRhs Quaternion
References Quaternion.
Quaternion& nc::rotations::Quaternion::operator-=(const Quaternion &inRhs) noexcept
subtraction assignment operator inRhs Quaternion
Quaternion nc::rotations::Quaternion::operator/(const Quaternion &inRhs) const noexcept
division operator inRhs Quaternion
References Quaternion.
Quaternion& nc::rotations::Quaternion::operator/=(const Quaternion &inRhs) noexcept
division assignment operator inRhs Quaternion
References conjugate.
bool nc::rotations::Quaternion::operator==(const Quaternion &inRhs) const noexcept
equality operator inRhs bool
References nc::utils::essentiallyEqual.
void nc::rotations::Quaternion::print() const noexcept
prints the Quaternion to the console
NdArray<double> nc::rotations::Quaternion::rotate(const NdArray< dtype > &inVector) const
rotate a vector using the quaternion inVector (cartesian vector with x,y,z components) NdArray<double> (cartesian vector with x,y,z components)
References nc::NdArray< dtype >::size.
double nc::rotations::Quaternion::s() const noexcept
returns the s componentdouble
Referenced by angleAxisRotation, conjugate, nlerp, str, toDCM.
Quaternion nc::rotations::Quaternion::slerp(const Quaternion &inQuat2, double inPercent) const
spherical linear interpolates between the two quaternions inQuat2 inPercent (0, 1) Quaternion
References slerp.
std::string nc::rotations::Quaternion::str() const noexcept
returns the quaternion as a string representationstd::string
References nc::utils::num2str, i, j, k, s.
NdArray<double> nc::rotations::Quaternion::toDCM() const noexcept
returns the direction cosine matrixNdArray<double>
References i, j, k, s, nc::utils::sqr.
Referenced by operator*, nc::rotations::DCM< dtype >::angleAxisRotation.
NdArray<double> nc::rotations::Quaternion::toNdArray() const
returns the quaternion as an NdArrayNdArray<double>
Referenced by slerp.
static Quaternion nc::rotations::Quaternion::angleAxisRotation(const NdArray< dtype > &inAxis, double inAngle)
returns a quaternion to rotate about the input axis by the input angle inAxis (x,y,z vector components) inAngle (radians) Quaternion
References nc::NdArray< dtype >::size, nc::NdArray< dtype >::norm, nc::NdArray< dtype >::item, i, nc::sin, j, k, s, nc::cos, Quaternion.
Referenced by nc::rotations::DCM< dtype >::angleAxisRotation.
static NdArray<double> nc::rotations::Quaternion::angularVelocity(const Quaternion &inQuat1, const Quaternion &inQuat2, double inTime) noexcept
angular velocity vector between the two quaternions. The norm of the array is the magnitude inQuat1 inQuat2 inTime (seperation time) NdArray<double>
References nc::NdArray< dtype >::zeros, nc::NdArray< dtype >::transpose, nc::NdArray< dtype >::dot.
Referenced by angularVelocity.
static Quaternion nc::rotations::Quaternion::fromDCM(const NdArray< dtype > &inDcm)
converts from a direction cosine matrix to a quaternion inDcm Quaternion
References nc::NdArray< dtype >::shape, nc::Shape::rows, nc::Shape::cols, nc::argmax, nc::sqrt, Quaternion.
static Quaternion nc::rotations::Quaternion::identity() noexcept
quaternion identity (0,0,0,1)Quaternion
References Quaternion.
static Quaternion nc::rotations::Quaternion::nlerp(const Quaternion &inQuat1, const Quaternion &inQuat2, double inPercent)
linearly interpolates between the two quaternions inQuat1 inQuat2 inPercent [0, 1] Quaternion
References nc::utils::essentiallyEqual, i, j, k, s, Quaternion.
Referenced by nlerp, slerp.
static Quaternion nc::rotations::Quaternion::slerp(const Quaternion &inQuat1, const Quaternion &inQuat2, double inPercent)
spherical linear interpolates between the two quaternions inQuat1 inQuat2 inPercent (0, 1) Quaternion
References toNdArray, nlerp, nc::clip, nc::cos, nc::sin, Quaternion.
Referenced by slerp.
static Quaternion nc::rotations::Quaternion::xRotation(double inAngle)
returns a quaternion to rotate about the x-axis by the input angle inAngle (radians) Quaternion
static Quaternion nc::rotations::Quaternion::yRotation(double inAngle)
returns a quaternion to rotate about the y-axis by the input angle inAngle (radians) Quaternion
static Quaternion nc::rotations::Quaternion::zRotation(double inAngle)
returns a quaternion to rotate about the y-axis by the input angle inAngle (radians) Quaternion
std::ostream& operator<<(std::ostream &inOStream, const Quaternion &inQuat) noexcept
IO operator for the Quaternion class inOStream inQuat std::ostream&