nc
Axis
Endian
Order
typedef int16_t nc::int16
typedef int32_t nc::int32
typedef int64_t nc::int64
typedef int8_t nc::int8
typedef uint16_t nc::uint16
typedef uint32_t nc::uint32
typedef uint64_t nc::uint64
typedef uint8_t nc::uint8
std::mt19937_64 nc::generator_
generator function
Referenced by nc::Random< dtype >::bernoulli, nc::Random< dtype >::beta, nc::Random< dtype >::binomial, nc::Random< dtype >::chiSquare, nc::Random< dtype >::cauchy, nc::Random< dtype >::discrete, nc::Random< dtype >::exponential, nc::Random< dtype >::extremeValue, nc::Random< dtype >::f, nc::Random< dtype >::gamma, nc::Random< dtype >::geometric, nc::Random< dtype >::laplace, nc::Random< dtype >::lognormal, nc::Random< dtype >::negativeBinomial, nc::Random< dtype >::nonCentralChiSquared, nc::Random< dtype >::normal, nc::Random< dtype >::permutation, nc::Random< dtype >::poisson, nc::Random< dtype >::rand, nc::Random< dtype >::randFloat, nc::Random< dtype >::randInt, nc::Random< dtype >::randN, nc::Random< dtype >::seed, nc::Random< dtype >::shuffle, nc::Random< dtype >::studentT, nc::Random< dtype >::triangle, nc::Random< dtype >::uniformOnSphere, nc::Random< dtype >::weibull.
dtype nc::abs(dtype inValue) noexcept
Calculate the absolute value.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.absolute.html inValue value
References abs.
Referenced by nc::coordinates::Dec::Dec, allclose, nc::NdArray< bool >::at, nc::utils::essentiallyEqual.
NdArray< dtype > nc::abs(const NdArray< dtype > &inArray) noexcept
Calculate the absolute value element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.absolute.html inArray NdArray
Referenced by abs, copySign, isclose, roll.
NdArray< dtype > nc::add(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2)
Add arguments element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.add.html inArray1 inArray2 NdArray
uint32 nc::alen(const NdArray< dtype > &inArray) noexcept
Return the length of the first dimension of the input array. inArray length uint16
NdArray< bool > nc::all(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Test whether all array elements along a given axis evaluate to True.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.all.html inArray inAxis (Optional, default NONE) bool
References nc::NdArray< dtype >::all.
Referenced by allclose.
bool nc::allclose(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2, double inTolerance=1e-5)
Returns True if two arrays are element-wise equal within a tolerance. inTolerance must be a positive numberNumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.allclose.html inArray1 inArray2 inTolerance (Optional, default 1e-5) bool
References nc::NdArray< dtype >::shape, all, abs, nc::NdArray< dtype >::item.
NdArray< dtype > nc::amax(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Return the maximum of an array or maximum along an axis.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.amax.html inArray inAxis (Optional, default NONE) max value
NdArray< dtype > nc::amin(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Return the minimum of an array or minimum along an axis.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.amin.html inArray inAxis (Optional, default NONE) min value
NdArray< bool > nc::any(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Test whether any array element along a given axis evaluates to True.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.any.html inArray inAxis (Optional, default NONE) NdArray
References nc::NdArray< dtype >::any.
NdArray< dtype > nc::append(const NdArray< dtype > &inArray, const NdArray< dtype > &inAppendValues, Axis inAxis=Axis::NONE)
Append values to the end of an array.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.append.html inArray inAppendValues inAxis (Optional, default NONE): The axis along which values are appended. If axis is not given, both inArray and inAppendValues are flattened before use. NdArray
References NONE, nc::NdArray< dtype >::size, copy, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend, ROW, nc::NdArray< dtype >::shape, nc::Shape::cols, nc::Shape::rows, nc::NdArray< dtype >::begin, COL.
NdArray<dtype> nc::applyFunction(const NdArray< dtype > &inArray, const std::function< dtype(dtype)> &inFunc) noexcept
void nc::applyFunction(NdArray< dtype > &inArray, const std::function< dtype(dtype)> &inFunc) noexcept
Apply the input function element wise to the input array in place. inArray inFunc NdArray
References nc::NdArray< dtype >::begin, nc::NdArray< dtype >::end.
void nc::applyPoly1d(NdArray< dtype > &inArray, const Poly1d< dtype > &inPoly) noexcept
Apply polynomial elemnt wise to the input values. inArray inPoly NdArray
NdArray< dtype > nc::arange(dtype inStart, dtype inStop, dtype inStep=1)
Return evenly spaced values within a given interval.Values are generated within the half - open interval[start, stop) (in other words, the interval including start but excluding stop). For integer arguments the function is equivalent to the Python built - in range function, but returns an ndarray rather than a list.When using a non - integer step, such as 0.1, the results will often not be consistent.It is better to use linspace for these cases.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.arange.html inStart inStop inStep (Optional, defaults to 1) NdArray
Referenced by nc::Random< dtype >::permutation.
NdArray< dtype > nc::arange(dtype inStop)
Return evenly spaced values within a given interval.Values are generated within the half - open interval[start, stop) (in other words, the interval including start but excluding stop). For integer arguments the function is equivalent to the Python built - in range function, but returns an ndarray rather than a list.When using a non - integer step, such as 0.1, the results will often not be consistent.It is better to use linspace for these cases.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.arange.html inStop start is 0 and step is 1 NdArray
NdArray< dtype > nc::arange(const Slice &inSlice)
Return evenly spaced values within a given interval.Values are generated within the half - open interval[start, stop) (in other words, the interval including start but excluding stop). For integer arguments the function is equivalent to the Python built - in range function, but returns an ndarray rather than a list.When using a non - integer step, such as 0.1, the results will often not be consistent.It is better to use linspace for these cases.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.arange.html inSlice NdArray
References nc::Slice::start, nc::Slice::stop, nc::Slice::step.
double nc::arccos(dtype inValue) noexcept
Trigonometric inverse cosineNumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.arccos.html inValue value
NdArray< double > nc::arccos(const NdArray< dtype > &inArray) noexcept
Trigonometric inverse cosine, element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.arccos.html inArray NdArray
References nc::NdArray< dtype >::shape, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend.
double nc::arccosh(dtype inValue) noexcept
Trigonometric inverse hyperbolic cosine.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.arccosh.html inValue value
NdArray< double > nc::arccosh(const NdArray< dtype > &inArray) noexcept
Trigonometric inverse hyperbolic cosine, element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.arccosh.html inArray NdArray
References nc::NdArray< dtype >::shape, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend.
double nc::arcsin(dtype inValue) noexcept
Trigonometric inverse sine.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.arcsin.html inValue value
NdArray< double > nc::arcsin(const NdArray< dtype > &inArray) noexcept
Trigonometric inverse sine, element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.arcsin.html inArray NdArray
References nc::NdArray< dtype >::shape, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend.
double nc::arcsinh(dtype inValue) noexcept
Trigonometric inverse hyperbolic sine.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.arcsinh.html inValue value
NdArray< double > nc::arcsinh(const NdArray< dtype > &inArray) noexcept
Trigonometric inverse hyperbolic sine, element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.arcsinh.html inArray NdArray
References nc::NdArray< dtype >::shape, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend.
double nc::arctan(dtype inValue) noexcept
Trigonometric inverse tangent.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.arctan.html inValue value
NdArray< double > nc::arctan(const NdArray< dtype > &inArray) noexcept
Trigonometric inverse tangent, element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.arctan.html inArray NdArray
double nc::arctan2(dtype inY, dtype inX) noexcept
Trigonometric inverse tangent.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.arctan2.html inY inX value
NdArray< double > nc::arctan2(const NdArray< dtype > &inY, const NdArray< dtype > &inX)
Trigonometric inverse tangent, element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.arctan2.html inY inX NdArray
References nc::NdArray< dtype >::shape, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend.
double nc::arctanh(dtype inValue) noexcept
Trigonometric inverse hyperbolic tangent.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.arctanh.html inValue value
NdArray< double > nc::arctanh(const NdArray< dtype > &inArray) noexcept
Trigonometric inverse hyperbolic tangent, element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.arctanh.html inArray NdArray
NdArray< uint32 > nc::argmax(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Returns the indices of the maximum values along an axis.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.argmax.html inArray inAxis (Optional, default NONE) NdArray
Referenced by nanargmax, nc::rotations::Quaternion::fromDCM.
NdArray< uint32 > nc::argmin(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Returns the indices of the minimum values along an axis.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.argmin.html inArray inAxis (Optional, default NONE) NdArray
Referenced by nanargmin.
NdArray< uint32 > nc::argsort(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Returns the indices that would sort an array.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.argsort.html inArray inAxis (Optional, default NONE) NdArray
Referenced by interp.
NdArray< uint32 > nc::argwhere(const NdArray< dtype > &inArray) noexcept
Find the indices of array elements that are non-zero, grouped by element.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.argwhere.html inArray NdArray
dtype nc::around(dtype inValue, uint8 inNumDecimals=0) noexcept
Evenly round to the given number of decimals.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.around.html inValue inNumDecimals (Optional, default = 0) value
References nc::NdArray< dtype >::round.
NdArray< dtype > nc::around(const NdArray< dtype > &inArray, uint8 inNumDecimals=0) noexcept
Evenly round to the given number of decimals.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.around.html inArray inNumDecimals (Optional, default = 0) NdArray
bool nc::array_equal(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2) noexcept
True if two arrays have the same shape and elements, False otherwise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.array_equal.html inArray1 inArray2 bool
References equal.
bool nc::array_equiv(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2) noexcept
Returns True if input arrays are shape consistent and all elements equal.Shape consistent means they are either the same shape, or one input array can be broadcasted to create the same shape as the other one.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.array_equiv.html inArray1 inArray2 bool
References equal.
NdArray< dtype > nc::asarray(const std::vector< dtype > &inVector) noexcept
Convert the vector to an array.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.asarray.html inVector NdArray
NdArray< dtype > nc::asarray(std::initializer_list< dtype > &inList) noexcept
Convert the list initializer to an array. eg: NdArray<int> myArray = NC::asarray<int>({1,2,3});NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.asarray.html inList NdArray
NdArray< dtypeOut > nc::astype(const NdArray< dtype > inArray) noexcept
Returns a copy of the array, cast to a specified type. inArray NdArray
NdArray< double > nc::average(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Compute the average along the specified axis.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.average.html inArray inAxis (Optional, default NONE) NdArray
References nc::NdArray< dtype >::mean.
NdArray< double > nc::average(const NdArray< dtype > &inArray, const NdArray< dtype > &inWeights, Axis inAxis=Axis::NONE)
Compute the weighted average along the specified axis.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.average.html inArray inWeights inAxis (Optional, default NONE) NdArray
References nc::NdArray< dtype >::shape, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend, sum, nc::NdArray< dtype >::size, nc::Shape::cols, nc::Shape::rows, nc::NdArray< dtype >::begin, nc::NdArray< dtype >::end, nc::NdArray< dtype >::transpose.
std::string nc::binaryRepr(dtype inValue) noexcept
Return the binary representation of the input number as a string.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.binary_repr.html inValue std::string
NdArray< dtype > nc::bincount(const NdArray< dtype > &inArray, uint16 inMinLength=0)
Count number of occurrences of each value in array of non-negative ints. Negative values will be counted in the zero bin.The number of bins(of size 1) is one larger than the largest value in x. If minlength is specified, there will be at least this number of bins in the output array(though it will be longer if necessary, depending on the contents of x).Each bin gives the number of occurrences of its index value in x.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.bincount.html inArray inMinLength NdArray
References nc::NdArray< dtype >::max, max, nc::NdArray< dtype >::clip, nc::NdArray< dtype >::zeros, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend.
NdArray< dtype > nc::bincount(const NdArray< dtype > &inArray, const NdArray< dtype > &inWeights, uint16 inMinLength=0)
Count number of occurrences of each value in array of non-negative ints. Negative values will be counted in the zero bin.The number of bins(of size 1) is one larger than the largest value in x. If minlength is specified, there will be at least this number of bins in the output array(though it will be longer if necessary, depending on the contents of x).Each bin gives the number of occurrences of its index value in x.If weights is specified the input array is weighted by it, i.e. if a value n is found at position i, out[n] += weight[i] instead of out[n] += 1. Weights array shall be of the same shape as inArray.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.bincount.html inArray inWeights inMinLength NdArray
References nc::NdArray< dtype >::shape, nc::NdArray< dtype >::max, max, nc::NdArray< dtype >::clip, nc::NdArray< dtype >::zeros, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend.
NdArray< dtype > nc::bitwise_and(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2)
Compute the bit-wise AND of two arrays element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.bitwise_and.html inArray1 inArray2 NdArray
NdArray< dtype > nc::bitwise_not(const NdArray< dtype > &inArray) noexcept
Compute the bit-wise NOT the input array element-wise.inArray NdArray
NdArray< dtype > nc::bitwise_or(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2)
Compute the bit-wise OR of two arrays element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.bitwise_or.html inArray1 inArray2 NdArray
NdArray< dtype > nc::bitwise_xor(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2)
Compute the bit-wise XOR of two arrays element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.bitwise_xor.html inArray1 inArray2 NdArray
NdArray<dtype> nc::boost2Nc(const boost::python::numpy::ndarray &inArray)
Converts from a boost ndarray to a NumCpp NdArray<T> inArray NdArray<T>
References nc::BoostNdarrayHelper::numDimensions, nc::Shape::rows, nc::Shape::cols, nc::BoostNdarrayHelper::shape, nc::Shape::size.
NdArray< dtype > nc::byteswap(const NdArray< dtype > &inArray) noexcept
Return a new array with the bytes of the array elements swapped. inArray NdArray
References nc::NdArray< dtype >::byteswap.
double nc::cbrt(dtype inValue) noexcept
Return the cube-root of an array. Not super usefull if not using a floating point typeNumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.cbrt.html inValue value
References cbrt.
NdArray< double > nc::cbrt(const NdArray< dtype > &inArray) noexcept
Return the cube-root of an array, element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.cbrt.html inArray NdArray
Referenced by cbrt.
dtype nc::ceil(dtype inValue) noexcept
Return the ceiling of the input.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ceil.html inValue value
References ceil.
Referenced by nc::filter::gaussianFilter, nc::filter::gaussianFilter1d.
NdArray< dtype > nc::ceil(const NdArray< dtype > &inArray) noexcept
Return the ceiling of the input, element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ceil.html inArray NdArray
Referenced by ceil, fix.
dtype nc::clip(dtype inValue, dtype inMinValue, dtype inMaxValue) noexcept
Clip (limit) the value.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.clip.html inValue inMinValue inMaxValue NdArray
Referenced by nc::rotations::Quaternion::slerp.
NdArray< dtype > nc::clip(const NdArray< dtype > &inArray, dtype inMinValue, dtype inMaxValue) noexcept
Clip (limit) the values in an array.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.clip.html inArray inMinValue inMaxValue NdArray
NdArray< dtype > nc::column_stack(const std::initializer_list< NdArray< dtype > > &inArrayList)
Stack 1-D arrays as columns into a 2-D array.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.column_stack.html inArrayList {list} of arrays to stack NdArray
References nc::Shape::isnull, nc::Shape::rows, nc::Shape::cols.
Referenced by concatenate, hstack, stack.
NdArray< dtype > nc::concatenate(const std::initializer_list< NdArray< dtype > > &inArrayList, Axis inAxis=Axis::NONE)
Join a sequence of arrays along an existing axis.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.concatenate.html inArrayList inAxis (Optional, default NONE) NdArray
References copy, nc::NdArray< dtype >::begin, row_stack, column_stack.
NdArray< bool > nc::contains(const NdArray< dtype > &inArray, dtype inValue, Axis inAxis=Axis::NONE) noexcept
returns whether or not a value is included the array inArray inValue inAxis (Optional, default NONE) bool
References nc::NdArray< dtype >::contains.
NdArray< dtype > nc::copy(const NdArray< dtype > &inArray) noexcept
Return an array copy of the given object.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.copy.html inArray NdArray
Referenced by append, concatenate, trim_zeros, nc::NdArray< bool >::NdArray, nc::NdArray< bool >::operator=, nc::NdArray< bool >::flatten, nc::NdArray< bool >::resizeSlow, nc::NdArray< bool >::operator++, nc::NdArray< bool >::operator--, nc::Poly1d< dtype >::operator*=.
NdArray< dtype > nc::copySign(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2)
Change the sign of x1 to that of x2, element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.copysign.html inArray1 inArray2 NdArray
References nc::NdArray< dtype >::shape, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend, abs.
NdArray< dtype > & nc::copyto(NdArray< dtype > &inDestArray, const NdArray< dtype > &inSrcArray) noexcept
Copies values from one array to anotherNumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.copyto.html inDestArray inSrcArray NdArray
double nc::cos(dtype inValue) noexcept
CosineNumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.cos.html inValue value
References cos.
Referenced by nc::rotations::Quaternion::angleAxisRotation, nc::rotations::Quaternion::slerp.
NdArray< double > nc::cos(const NdArray< dtype > &inArray) noexcept
Cosine element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.cos.html inArray NdArray
Referenced by cos, unwrap.
double nc::cosh(dtype inValue) noexcept
Hyperbolic Cosine.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.cosh.html inValue value
References cosh.
NdArray< double > nc::cosh(const NdArray< dtype > &inArray) noexcept
Hyperbolic Cosine element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.cosh.html inArray NdArray
Referenced by cosh.
NdArray< uint32 > nc::count_nonzero(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Counts the number of non-zero values in the array.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.count_nonzero.html inArray inAxis (Optional, default NONE) NdArray
References nc::NdArray< dtype >::size, nc::Shape::rows, nc::Shape::cols, nc::NdArray< dtype >::transpose, nc::NdArray< dtype >::shape, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend.
NdArray< dtype > nc::cross(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2, Axis inAxis=Axis::NONE)
Return the cross product of two (arrays of) vectors.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.cross.html inArray1 inArray2 inAxis (Optional, default NONE) NdArray
References nc::NdArray< dtype >::shape, nc::NdArray< dtype >::size, nc::NdArray< dtype >::flatten, nc::Shape::rows, nc::Shape::cols, nc::NdArray< dtype >::put.
dtype nc::cube(dtype inValue) noexcept
Cubes the input inValue cubed value
References cube.
NdArray< dtype > nc::cube(const NdArray< dtype > &inArray) noexcept
Cubes the elements of the array inArray NdArray
Referenced by cube.
NdArray< dtype > nc::cumprod(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Return the cumulative product of elements along a given axis.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.cumprod.html inArray inAxis (Optional, default NONE) NdArray
Referenced by nancumprod.
NdArray< dtype > nc::cumsum(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Return the cumulative sum of the elements along a given axis.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.cumsum.html inArray inAxis (Optional, default NONE) NdArray
Referenced by nancumsum.
double nc::deg2rad(dtype inValue) noexcept
Convert angles from degrees to radians.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.deg2rad.html inValue value
References nc::constants::pi.
Referenced by nc::coordinates::RA::RA, nc::coordinates::Dec::Dec.
NdArray< double > nc::deg2rad(const NdArray< dtype > &inArray=Axis::NONE) noexcept
Convert angles from degrees to radians.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.deg2rad.html inArray NdArray
Referenced by radians.
double nc::degrees(dtype inValue) noexcept
Convert angles from degrees to radians.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.degrees.html inValue value
References rad2deg.
NdArray< double > nc::degrees(const NdArray< dtype > &inArray=Axis::NONE) noexcept
Convert angles from degrees to radians.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.degrees.html inArray NdArray
References rad2deg.
NdArray< dtype > nc::deleteIndices(const NdArray< dtype > &inArray, const NdArray< uint32 > &inArrayIdxs, Axis inAxis=Axis::NONE)
Return a new array with sub-arrays along an axis deleted. inArray inArrayIdxs inAxis (Optional, default NONE) if none the indices will be applied to the flattened array NdArray
References unique, nc::NdArray< dtype >::size, nc::NdArray< dtype >::contains, nc::NdArray< dtype >::item, nc::NdArray< dtype >::shape, nc::NdArray< dtype >::max, nc::Shape::rows, nc::Shape::cols.
NdArray< dtype > nc::deleteIndices(const NdArray< dtype > &inArray, const Slice &inIndicesSlice, Axis inAxis=Axis::NONE)
Return a new array with sub-arrays along an axis deleted. inArray inIndicesSlice inAxis (Optional, default NONE) if none the indices will be applied to the flattened array NdArray
References nc::Slice::makePositiveAndValidate, nc::NdArray< dtype >::size, nc::NdArray< dtype >::shape, nc::Slice::start, nc::Slice::stop, nc::Slice::step, deleteIndices.
NdArray< dtype > nc::deleteIndices(const NdArray< dtype > &inArray, uint32 inIndex, Axis inAxis=Axis::NONE)
Return a new array with sub-arrays along an axis deleted. inArray inIndex inAxis (Optional, default NONE) if none the indices will be applied to the flattened array NdArray
Referenced by deleteIndices.
NdArray< dtype > nc::diagflat(const NdArray< dtype > &inArray) noexcept
Create a two-dimensional array with the flattened input as a diagonal.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.diagflat.html inArray NdArray
References nc::NdArray< dtype >::zeros.
Referenced by nc::linalg::svd.
NdArray< dtype > nc::diagonal(const NdArray< dtype > &inArray, int32 inOffset=0, Axis inAxis=Axis::ROW) noexcept
Return specified diagonals.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.diagonal.html inArray inOffset (Defaults to 0) inAxis (Optional, default NONE) axis the offset is applied to NdArray
NdArray< dtype > nc::diff(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Calculate the n-th discrete difference along given axis. Unsigned dtypes will give you weird results...obviously.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.diff.html inArray inAxis (Optional, default NONE) NdArray
References nc::Shape::cols, nc::Shape::rows, nc::NdArray< dtype >::begin, nc::NdArray< dtype >::transpose, nc::NdArray< dtype >::shape, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend.
NdArray< dtype > nc::divide(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2)
Returns a true division of the inputs, element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.divide.html inArray1 inArray2 NdArray
NdArray< dtype > nc::dot(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2)
Dot product of two arrays.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.dot.html inArray1 inArray2 NdArray
References nc::NdArray< dtype >::dot.
Referenced by nc::coordinates::Coordinate::radianSeperation, nc::filter::convolve, nc::filter::convolve1d, nc::linalg::matrix_power, nc::linalg::multi_dot.
void nc::dump(const NdArray< dtype > &inArray, const std::string &inFilename)
Dump a binary file of the array to the specified file. The array can be read back with or NC::load. inArray inFilename NdArray
References nc::NdArray< dtype >::dump.
Referenced by nc::NdArray< bool >::tofile.
NdArray< dtype > nc::empty(uint32 inNumRows, uint32 inNumCols) noexcept
Return a new array of given shape and type, without initializing entries.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.empty.html inNumRows inNumCols NdArray
NdArray< dtype > nc::empty(const Shape &inShape) noexcept
Return a new array of given shape and type, without initializing entries.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.empty.html inShape NdArray
NdArray< dtype > nc::empty_like(const NdArray< dtype > &inArray) noexcept
Return a new array with the same shape as a given array.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.empty_like.html inArray NdArray
Endian nc::endianess(const NdArray< dtype > &inArray) noexcept
Return the endianess of the array values. inArray Endian
NdArray< bool > nc::equal(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2)
Return (x1 == x2) element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.equal.html inArray1 inArray2 NdArray
Referenced by nc::BoostNdarrayHelper::shapeEqual, nc::imageProcessing::Cluster< dtype >::operator==, array_equal, array_equiv.
double nc::erf(dtype inValue) noexcept
Calculate the error function of all elements in the input array. Integral (from [-x, x]) of np.exp(np.power(-t, 2)) dt, multiplied by 1/np.pi. inValue double
References erf.
NdArray< double > nc::erf(const NdArray< dtype > &inArray) noexcept
Calculate the error function of all elements in the input array. Integral (from [-x, x]) of np.exp(np.power(-t, 2)) dt, multiplied by 1/np.pi. inArray NdArray<double>
Referenced by erf.
double nc::erfc(dtype inValue) noexcept
Returns the complement of the error function of inValue. inValue double
References erfc.
NdArray<double> nc::erfc(const NdArray< dtype > &inArray) noexcept
Returns the element-wise complement of the error function of inValue. inArray NdArray<double>
Referenced by erfc.
double nc::exp(dtype inValue) noexcept
Calculate the exponential of the input value.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.exp.html inValue value
References exp.
Referenced by nc::filter::gaussian.
NdArray< double > nc::exp(const NdArray< dtype > &inArray) noexcept
Calculate the exponential of all elements in the input array.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.exp.html inArray NdArray
Referenced by exp, expm1.
double nc::exp2(dtype inValue) noexcept
Calculate 2**p for all p in the input value.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.exp2.html inValue value
References exp2.
NdArray< double > nc::exp2(const NdArray< dtype > &inArray) noexcept
Calculate 2**p for all p in the input array.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.exp2.html inArray NdArray
Referenced by exp2.
double nc::expm1(dtype inValue) noexcept
Calculate exp(x) - 1 for the input value.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.expm1.html inValue value
References exp.
NdArray< double > nc::expm1(const NdArray< dtype > &inArray) noexcept
Calculate exp(x) - 1 for all elements in the array.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.expm1.html inArray NdArray
NdArray< dtype > nc::eye(uint32 inN, int32 inK=0) noexcept
Return a 2-D array with ones on the diagonal and zeros elsewhere.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.eye.html inN number of rows and columns (N) inK Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal. NdArray
NdArray< dtype > nc::eye(uint32 inN, uint32 inM, int32 inK=0) noexcept
Return a 2-D array with ones on the diagonal and zeros elsewhere.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.eye.html inN number of rows (N) inM number of columns (M) inK Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal. NdArray
References nc::NdArray< dtype >::zeros.
NdArray< dtype > nc::eye(const Shape &inShape, int32 inK=0) noexcept
Return a 2-D array with ones on the diagonal and zeros elsewhere.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.eye.html inShape inK Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal. NdArray
void nc::fillDiagonal(NdArray< dtype > &inArray, dtype inValue) noexcept
Fill the main diagonal of the given array.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.fill_diagonal.html inArray inValue
NdArray< uint32 > nc::find(const NdArray< bool > &mask, uint32 n=std::numeric_limits< uint32 >::max()) noexcept
Find flat indices of nonzero elements. mask the mask to apply to the array n the first n indices to return (optional, default all) NdArray
References nc::NdArray< dtype >::nonzero, nc::NdArray< dtype >::size.
Referenced by nc::NdArray< bool >::contains.
dtype nc::fix(dtype inValue) noexcept
Round to nearest integer towards zero.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.fix.html inValue value
References floor, ceil.
NdArray< dtype > nc::fix(const NdArray< dtype > &inArray) noexcept
Round to nearest integer towards zero.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.fix.html inArray NdArray
NdArray< uint32 > nc::flatnonzero(const NdArray< dtype > &inArray) noexcept
Return indices that are non-zero in the flattened version of a.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.flatnonzero.html inArray NdArray
NdArray< dtype > nc::flatten(const NdArray< dtype > &inArray) noexcept
Return a copy of the array collapsed into one dimension. inArray NdArray
NdArray< dtype > nc::flip(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Reverse the order of elements in an array along the given axis.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.flip.html inArray inAxis NdArray
References nc::NdArray< dtype >::begin, nc::NdArray< dtype >::end, nc::NdArray< dtype >::transpose, nc::NdArray< dtype >::shape.
Referenced by fliplr, flipud, rot90.
NdArray< dtype > nc::fliplr(const NdArray< dtype > &inArray) noexcept
Flip array in the left/right direction.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.fliplr.html inArray NdArray
References flip.
Referenced by nc::filter::reflectBoundary1d, nc::filter::mirrorBoundary1d, nc::filter::convolve1d, rot90.
NdArray< dtype > nc::flipud(const NdArray< dtype > &inArray) noexcept
Flip array in the up/down direction.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.flipud.html inArray NdArray
References flip.
Referenced by nc::filter::reflectBoundary, nc::filter::mirrorBoundary, rot90.
dtype nc::floor(dtype inValue) noexcept
Return the floor of the input.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.floor.html inValue value
References floor.
Referenced by nc::coordinates::RA::RA, nc::coordinates::Dec::Dec, nc::imageProcessing::generateThreshold.
NdArray< dtype > nc::floor(const NdArray< dtype > &inArray) noexcept
Return the floor of the input, element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.floor.html inArray NdArray
Referenced by fix, floor, floor_divide, nanpercentile, percentile.
dtype nc::floor_divide(dtype inValue1, dtype inValue2) noexcept
Return the largest integer smaller or equal to the division of the inputs.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.floor_divide.html inValue1 inValue2 value
References floor.
NdArray< dtype > nc::floor_divide(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2)
Return the largest integer smaller or equal to the division of the inputs.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.floor_divide.html inArray1 inArray2 NdArray
References floor.
dtype nc::fmax(dtype inValue1, dtype inValue2) noexcept
maximum of inputs.Compare two value and returns a value containing the maximaNumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.fmax.html inValue1 inValue2 value
References max.
NdArray< dtype > nc::fmax(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2)
Element-wise maximum of array elements.Compare two arrays and returns a new array containing the element - wise maximaNumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.fmax.html inArray1 inArray2 NdArray
References nc::NdArray< dtype >::shape, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend, max.
dtype nc::fmin(dtype inValue1, dtype inValue2) noexcept
minimum of inputs.Compare two value and returns a value containing the minimaNumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.fmin.html inValue1 inValue2 value
References min.
NdArray< dtype > nc::fmin(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2)
Element-wise minimum of array elements.Compare two arrays and returns a new array containing the element - wise minimaNumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.fmin.html inArray1 inArray2 NdArray
References nc::NdArray< dtype >::shape, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend, min.
dtype nc::fmod(dtype inValue1, dtype inValue2) noexcept
Return the remainder of division.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.fmod.html inValue1 inValue2 value
NdArray< dtype > nc::fmod(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2)
Return the element-wise remainder of division.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.fmod.html inArray1 inArray2 NdArray
References nc::NdArray< dtype >::shape, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend.
NdArray< dtype > nc::frombuffer(char *inBufferPtr, uint32 inNumBytes) noexcept
Interpret a buffer as a 1-dimensional array.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.frombuffer.html inBufferPtr inNumBytes NdArray
NdArray< dtype > nc::fromfile(const std::string &inFilename, const std::string &inSep="")
Construct an array from data in a text or binary file.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.fromfile.html inFilename inSep Separator between items if file is a text file. Empty ("") separator means the file should be treated as binary. Right now the only supported seperators are " ", "\t", "\n" NdArray
NdArray< dtype > nc::fromiter(Iter inBegin, Iter inEnd) noexcept
Create a new 1-dimensional array from an iterable object.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.fromiter.html inBegin inEnd NdArray
NdArray< dtype > nc::full(uint32 inSquareSize, dtype inFillValue) noexcept
Return a new array of given shape and type, filled with inFillValueNumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.full.html inSquareSize inFillValue NdArray
References nc::NdArray< dtype >::fill.
NdArray< dtype > nc::full(uint32 inNumRows, uint32 inNumCols, dtype inFillValue) noexcept
Return a new array of given shape and type, filled with inFillValueNumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.full.html inNumRows inNumCols inFillValue NdArray
References nc::NdArray< dtype >::fill.
NdArray< dtype > nc::full(const Shape &inShape, dtype inFillValue) noexcept
Return a new array of given shape and type, filled with inFillValueNumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.full.html inShape inFillValue NdArray
Referenced by full_like, nans, ones, zeros.
NdArray< dtype > nc::full_like(const NdArray< dtype > &inArray, dtype inFillValue) noexcept
Return a full array with the same shape and type as a given array.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.full_like.html inArray inFillValue NdArray
References full.
dtype nc::gcd(dtype inValue1, dtype inValue2) noexcept
Returns the greatest common divisor of |x1| and |x2|NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.gcd.html inValue1 inValue2 dtype
References gcd.
dtype nc::gcd(const NdArray< dtype > &inArray) noexcept
Returns the greatest common divisor of the values in the input array.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.gcd.html inArray NdArray<double>
Referenced by gcd.
NdArray< double > nc::gradient(const NdArray< dtype > &inArray, Axis inAxis=Axis::ROW)
Return the gradient of the array.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.gradient.html inArray inAxis (default ROW) NdArray
References nc::NdArray< dtype >::shape, nc::NdArray< dtype >::size, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend, nc::NdArray< dtype >::begin.
NdArray< bool > nc::greater(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2)
Return the truth value of (x1 > x2) element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.greater.html inArray1 inArray2 NdArray
NdArray< bool > nc::greater_equal(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2)
Return the truth value of (x1 >= x2) element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.greater_equal.html inArray1 inArray2 NdArray
std::pair< NdArray< uint32 >, NdArray< double > > nc::histogram(const NdArray< dtype > &inArray, uint32 inNumBins=10)
Compute the histogram of a set of data.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.histogram.html inArray inNumBins( default 10) std::pair of NdArrays; first is histogram counts, seconds is the bin edges
References linspace, nc::NdArray< dtype >::min, nc::NdArray< dtype >::max, nc::NdArray< dtype >::size.
Referenced by nc::imageProcessing::generateThreshold.
NdArray< dtype > nc::hstack(const std::initializer_list< NdArray< dtype > > &inArrayList)
Stack arrays in sequence horizontally (column wise).NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.hstack.html inArrayList {list} of arrays to stack NdArray
References column_stack.
double nc::hypot(dtype inValue1, dtype inValue2) noexcept
Given the "legs" of a right triangle, return its hypotenuse.Equivalent to sqrt(x1**2 + x2 * *2), element - wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.hypot.html inValue1 inValue2 NdArray
References hypot.
NdArray< double > nc::hypot(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2)
Given the "legs" of a right triangle, return its hypotenuse.Equivalent to sqrt(x1**2 + x2**2), element - wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.hypot.html inArray1 inArray2 NdArray
References nc::NdArray< dtype >::shape, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend.
Referenced by hypot.
NdArray< dtype > nc::identity(uint32 inSquareSize) noexcept
Return the identity array.The identity array is a square array with ones on the main diagonal.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.identity.html inSquareSize NdArray
References nc::NdArray< dtype >::zeros.
double nc::interp(dtype inValue1, dtype inValue2, double inPercent) noexcept
Returns the linear interpolation between two points inValue1 inValue2 inPercent linear interpolated point
References interp.
NdArray< dtype > nc::interp(const NdArray< dtype > &inX, const NdArray< dtype > &inXp, const NdArray< dtype > &inFp)
One-dimensional linear interpolation.Returns the one - dimensional piecewise linear interpolant to a function with given values at discrete data - points. If input arrays are not one dimensional they will be internally flattened.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.interp.html inX The x-coordinates at which to evaluate the interpolated values. inXp The x-coordinates of the data points, must be increasing. Otherwise, xp is internally sorted. inFp The y-coordinates of the data points, same length as inXp. NdArray
References nc::NdArray< dtype >::size, nc::NdArray< dtype >::min, nc::NdArray< dtype >::max, argsort, sort.
Referenced by interp.
NdArray< dtype > nc::intersect1d(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2)
Find the intersection of two arrays.Return the sorted, unique values that are in both of the input arrays.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.intersect1d.html inArray1 inArray2 NdArray
References nc::NdArray< dtype >::size, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend.
NdArray< dtype > nc::invert(const NdArray< dtype > &inArray) noexcept
Compute bit-wise inversion, or bit-wise NOT, element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.invert.html inArray NdArray
NdArray< bool > nc::isclose(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2, double inRtol=1e-05, double inAtol=1e-08)
Returns a boolean array where two arrays are element-wise equal within a tolerance.For finite values, isclose uses the following equation to test whether two floating point values are equivalent. absolute(a - b) <= (atol + rtol * absolute(b))NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.isclose.html inArray1 inArray2 inRtol relative tolerance (default 1e-5) inAtol absolute tolerance (default 1e-9) NdArray
References nc::NdArray< dtype >::shape, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend, abs.
bool nc::isinf(dtype inValue) noexcept
Test for inf and return result as a boolean.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.isinf.html inValue bool
References isinf.
NdArray< bool > nc::isinf(const NdArray< dtype > &inArray) noexcept
Test element-wise for inf and return result as a boolean array.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.isinf.html inArray NdArray
Referenced by isinf.
bool nc::isnan(dtype inValue) noexcept
Test for NaN and return result as a boolean.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.isnan.html inValue bool
References isnan.
NdArray< bool > nc::isnan(const NdArray< dtype > &inArray) noexcept
Test element-wise for NaN and return result as a boolean array.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.isnan.html inArray NdArray
Referenced by isnan, nanargmax, nanargmin, nancumprod, nancumsum, nanmax, nanmean, nanmedian, nanmin, nanpercentile, nanprod, nanstdev, nansum.
dtype nc::lcm(dtype inValue1, dtype inValue2) noexcept
Returns the least common multiple of |x1| and |x2|NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.lcm.html inValue1 inValue2 dtype
References lcm.
NdArray<dtype> nc::lcm(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2) noexcept
dtype nc::lcm(const NdArray< dtype > &inArray) noexcept
Returns the least common multiple of the values of the input array.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.lcm.html inArray NdArray<double>
Referenced by lcm.
dtype nc::ldexp(dtype inValue1, uint8 inValue2) noexcept
Returns x1 * 2^x2.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ldexp.html inValue1 inValue2 value
References ldexp.
NdArray< dtype > nc::ldexp(const NdArray< dtype > &inArray1, const NdArray< uint8 > &inArray2)
Returns x1 * 2^x2, element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ldexp.html inArray1 inArray2 NdArray
References nc::NdArray< dtype >::shape, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend.
Referenced by ldexp.
NdArray< dtype > nc::left_shift(const NdArray< dtype > &inArray, uint8 inNumBits) noexcept
Shift the bits of an integer to the left.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.left_shift.html inArray inNumBits NdArray
NdArray< bool > nc::less(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2)
Return the truth value of (x1 < x2) element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.less.html inArray1 inArray2 NdArray
NdArray< bool > nc::less_equal(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2)
Return the truth value of (x1 <= x2) element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.less_equal.html inArray1 inArray2 NdArray
NdArray< dtype > nc::linspace(dtype inStart, dtype inStop, uint32 inNum=50, bool endPoint=true)
Return evenly spaced numbers over a specified interval.Returns num evenly spaced samples, calculated over the interval[start, stop].The endpoint of the interval can optionally be excluded.Mostly only usefull if called with a floating point type for the template argument.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.linspace.html inStart inStop inNum number of points (default = 50) endPoint include endPoint (default = true) NdArray
Referenced by histogram.
std::vector<T> nc::list2vector(const boost::python::list &inList) noexcept
converts a boost python list to a std::vector inList std::vector<T>
NdArray< dtype > nc::load(const std::string &inFilename)
loads a .bin file from the dump() method into an NdArrayNumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.load.html inFilename NdArray
double nc::log(dtype inValue) noexcept
Natural logarithm.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.log.html inValue value
References log.
NdArray< double > nc::log(const NdArray< dtype > &inArray) noexcept
Natural logarithm, element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.log.html inArray NdArray
Referenced by log.
double nc::log10(dtype inValue) noexcept
Return the base 10 logarithm of the input array.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.log10.html inValue value
References log10.
NdArray< double > nc::log10(const NdArray< dtype > &inArray) noexcept
Return the base 10 logarithm of the input array, element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.log10.html inArray NdArray
Referenced by log10.
double nc::log1p(dtype inValue) noexcept
Return the natural logarithm of one plus the input array.Calculates log(1 + x).NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.log1p.html inValue value
References log1p.
NdArray< double > nc::log1p(const NdArray< dtype > &inArray) noexcept
Return the natural logarithm of one plus the input array, element-wise.Calculates log(1 + x).NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.log1p.html inArray NdArray
Referenced by log1p.
double nc::log2(dtype inValue) noexcept
Base-2 logarithm of x.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.log2.html inValue value
References log2.
NdArray< double > nc::log2(const NdArray< dtype > &inArray) noexcept
Base-2 logarithm of x.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.log2.html inArray NdArray
Referenced by log2.
NdArray< bool > nc::logical_and(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2)
Compute the truth value of x1 AND x2 element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.logical_and.html inArray1 inArray2 NdArray
References nc::NdArray< dtype >::shape, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend.
NdArray< bool > nc::logical_not(const NdArray< dtype > &inArray) noexcept
Compute the truth value of NOT x element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.logical_not.html inArray NdArray
NdArray< bool > nc::logical_or(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2)
Compute the truth value of x1 OR x2 element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.logical_or.html inArray1 inArray2 NdArray
References nc::NdArray< dtype >::shape, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend.
NdArray< bool > nc::logical_xor(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2)
Compute the truth value of x1 XOR x2 element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.logical_xor.html inArray1 inArray2 NdArray
References nc::NdArray< dtype >::shape, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend.
boost::python::dict nc::map2dict(const std::map< Key, Value > &inMap) noexcept
converts a std::map in to a boost python dictionary inMap boost::python::dict
NdArray< dtype > nc::matmul(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2)
Matrix product of two arrays.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.matmul.html inArray1 inArray2 NdArray
References nc::NdArray< dtype >::dot.
NdArray< dtype > nc::max(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Return the maximum of an array or maximum along an axis. inArray inAxis (Optional, default NONE) NdArray
Referenced by nc::DtypeInfo< dtype >::max, nc::filter::gaussianFilter, nc::filter::gaussianFilter1d, nc::imageProcessing::windowExceedances, bincount, fmax, maximum, nanargmin, nanmax, nanmin.
NdArray< dtype > nc::maximum(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2)
Element-wise maximum of array elements.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.maximum.html inArray1 inArray2 NdArray
References nc::NdArray< dtype >::shape, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend, max.
NdArray< double > nc::mean(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Compute the mean along the specified axis.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.mean.html inArray inAxis (Optional, default NONE) NdArray
References nc::NdArray< dtype >::mean.
NdArray< dtype > nc::median(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Compute the median along the specified axis.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.median.html inArray inAxis (Optional, default NONE) NdArray
std::pair< NdArray< dtype >, NdArray< dtype > > nc::meshgrid(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2) noexcept
Return coordinate matrices from coordinate vectors. Make 2D coordinate arrays for vectorized evaluations of 2D scalar vector fields over 2D grids, given one - dimensional coordinate arrays x1, x2, ..., xn. If input arrays are not one dimensional they will be flattened.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.meshgrid.html inICoords inJCoords std::pair<NdArray<dtype>, NdArray<dtype> >, i and j matrices
std::pair< NdArray< dtype >, NdArray< dtype > > nc::meshgrid(const Slice &inSlice1, const Slice &inSlice2) noexcept
Return coordinate matrices from coordinate vectors. Make 2D coordinate arrays for vectorized evaluations of 2D scalar vector fields over 2D grids, given one - dimensional coordinate arrays x1, x2, ..., xn.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.meshgrid.html inSlice1 inSlice2 std::pair<NdArray<dtype>, NdArray<dtype> >, i and j matrices
NdArray< dtype > nc::min(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Return the minimum of an array or maximum along an axis. inArray inAxis (Optional, default NONE) NdArray
Referenced by nc::DtypeInfo< dtype >::min, fmin, minimum, nanargmax, nanmax, nanmin.
NdArray< dtype > nc::minimum(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2)
Element-wise minimum of array elements.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.minimum.html inArray1 inArray2 NdArray
References nc::NdArray< dtype >::shape, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend, min.
NdArray< dtype > nc::mod(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2)
Return element-wise remainder of division.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.mod.html inArray1 inArray2 NdArray
NdArray< dtype > nc::multiply(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2)
Multiply arguments element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.multiply.html inArray1 inArray2 NdArray
NdArray< uint32 > nc::nanargmax(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Returns the indices of the maximum values along an axis ignoring NaNs.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.nanargmax.html inArray inAxis (Optional, default NONE) NdArray
References nc::NdArray< dtype >::begin, nc::NdArray< dtype >::end, isnan, min, argmax.
NdArray< uint32 > nc::nanargmin(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Returns the indices of the minimum values along an axis ignoring NaNs.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.nanargmin.html inArray inAxis (Optional, default NONE) NdArray
References nc::NdArray< dtype >::begin, nc::NdArray< dtype >::end, isnan, max, argmin.
NdArray< dtype > nc::nancumprod(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Return the cumulative product of elements along a given axis ignoring NaNs.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.nancumprod.html inArray inAxis (Optional, default NONE) NdArray
References nc::NdArray< dtype >::begin, nc::NdArray< dtype >::end, isnan, cumprod.
NdArray< dtype > nc::nancumsum(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Return the cumulative sum of the elements along a given axis ignoring NaNs.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.nancumsum.html inArray inAxis (Optional, default NONE) NdArray
References nc::NdArray< dtype >::begin, nc::NdArray< dtype >::end, isnan, cumsum.
NdArray< dtype > nc::nanmax(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Return the maximum of an array or maximum along an axis ignoring NaNs.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.nanmax.html inArray inAxis (Optional, default NONE) NdArray
References nc::NdArray< dtype >::begin, nc::NdArray< dtype >::end, isnan, min, max.
NdArray< double > nc::nanmean(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Compute the mean along the specified axis ignoring NaNs.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.nanmean.html inArray inAxis (Optional, default NONE) NdArray
References sum, isnan, nc::Shape::rows, nc::NdArray< dtype >::transpose, nc::NdArray< dtype >::shape, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend.
Referenced by nanstdev.
NdArray< dtype > nc::nanmedian(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Compute the median along the specified axis ignoring NaNs.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.nanmedian.html inArray inAxis (Optional, default NONE) NdArray
References isnan, nc::Shape::rows, nc::Shape::cols, nc::NdArray< dtype >::transpose, nc::NdArray< dtype >::shape.
NdArray< dtype > nc::nanmin(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Return the minimum of an array or maximum along an axis ignoring NaNs.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.nanmin.html inArray inAxis (Optional, default NONE) NdArray
References nc::NdArray< dtype >::begin, nc::NdArray< dtype >::end, isnan, max, min.
NdArray< dtype > nc::nanpercentile(const NdArray< dtype > &inArray, double inPercentile, Axis inAxis=Axis::NONE, const std::string &inInterpMethod="linear")
Compute the qth percentile of the data along the specified axis, while ignoring nan values.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.nanpercentile.html inArray inPercentile inAxis (Optional, default NONE) inInterpMethod (default linear) choices = ['linear','lower','higher','nearest','midpoint'] NdArray
References nc::utils::essentiallyEqual, isnan, nc::NdArray< dtype >::size, floor, sort, nc::NdArray< dtype >::shape, nc::Shape::rows, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend, nc::NdArray< dtype >::item, nc::constants::nan, nc::NdArray< dtype >::transpose.
NdArray< dtype > nc::nanprod(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Return the product of array elements over a given axis treating Not a Numbers (NaNs) as ones.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.nanprod.html inArray inAxis (Optional, default NONE) NdArray
References nc::NdArray< dtype >::begin, nc::NdArray< dtype >::end, isnan, prod.
NdArray< double > nc::nans(uint32 inSquareSize) noexcept
Return a new array of given shape and type, filled with nans. Only really works for dtype = float/double inSquareSize NdArray
References full, nc::constants::nan.
NdArray< double > nc::nans(uint32 inNumRows, uint32 inNumCols) noexcept
Return a new array of given shape and type, filled with nans. Only really works for dtype = float/double inNumRows inNumCols NdArray
References full, nc::constants::nan.
NdArray< double > nc::nans(const Shape &inShape) noexcept
Return a new array of given shape and type, filled with nans. Only really works for dtype = float/double inShape NdArray
References full, nc::constants::nan.
NdArray< double > nc::nans_like(const NdArray< dtype > &inArray) noexcept
Return a new array of given shape and type, filled with nans. inArray NdArray
References nc::NdArray< dtype >::nans.
NdArray< double > nc::nanstdev(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Compute the standard deviation along the specified axis, while ignoring NaNs.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.nanstd.html inArray inAxis (Optional, default NONE) NdArray
References nanmean, nc::NdArray< dtype >::item, sum, isnan, nc::utils::sqr, sqrt, nc::Shape::rows, nc::Shape::cols, nc::NdArray< dtype >::transpose, nc::NdArray< dtype >::shape.
Referenced by nanvar.
NdArray< dtype > nc::nansum(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Return the sum of array elements over a given axis treating Not a Numbers (NaNs) as zero.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.nansum.html inArray inAxis (Optional, default NONE) NdArray
References nc::NdArray< dtype >::begin, nc::NdArray< dtype >::end, isnan, sum.
NdArray< double > nc::nanvar(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Compute the variance along the specified axis, while ignoring NaNs.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.nanvar.html inArray inAxis (Optional, default NONE) NdArray
References square, nanstdev.
uint64 nc::nbytes(const NdArray< dtype > &inArray) noexcept
Returns the number of bytes held by the array inArray number of bytes
boost::python::numpy::ndarray nc::nc2Boost(const NdArray< dtype > &inArray) noexcept
Converts from a NumCpp NdArray<T> to a boost ndarray inArray ndarray
References shape, nc::Shape::rows, nc::Shape::cols, nc::BoostNdarrayHelper::getArray.
pybind11::array_t<dtype> nc::nc2pybind(NdArray< dtype > &inArray, bool transferOwnership=true) noexcept
converts a numcpp NdArray to numpy array using pybind bindings inArray the input array transferOwnership whether or not to transfer ownership to python. Requires that the NdArray owns its data. pybind11::array_t
References nc::NdArray< dtype >::shape, shape, nc::Shape::rows, nc::Shape::cols, nc::NdArray< dtype >::ownsInternalData, nc::NdArray< dtype >::begin, nc::NdArray< dtype >::dataRelease, nc::NdArray< dtype >::data.
NdArray< dtype > nc::negative(const NdArray< dtype > &inArray) noexcept
Numerical negative, element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.negative.html inArray NdArray
References nc::NdArray< dtype >::copy.
dtype nc::newbyteorder(dtype inValue, Endian inEndianess) noexcept
Return the array with the same data viewed with a different byte order. only works for integer types, floating point types will not compile and you will be confused as to why... inValue inEndianess inValue
References nc::NdArray< dtype >::newbyteorder.
NdArray< dtype > nc::newbyteorder(const NdArray< dtype > &inArray, Endian inEndianess) noexcept
Return the array with the same data viewed with a different byte order. only works for integer types, floating point types will not compile and you will be confused as to why... inArray inEndianess NdArray
NdArray< uint32 > nc::nonzero(const NdArray< dtype > &inArray) noexcept
Return the indices of the flattened array of the elements that are non-zero.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.nonzero.html inArray NdArray
NdArray< double > nc::norm(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Matrix or vector norm. inArray inAxis (Optional, default NONE) NdArray
References nc::NdArray< dtype >::norm.
Referenced by nc::rotations::Quaternion::Quaternion.
NdArray< bool > nc::not_equal(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2)
Return (x1 != x2) element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.not_equal.html inArray1 inArray2 NdArray
NdArray< dtype > nc::ones(uint32 inSquareSize) noexcept
Return a new array of given shape and type, filled with ones.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ones.html inSquareSize NdArray
References full.
NdArray< dtype > nc::ones(uint32 inNumRows, uint32 inNumCols) noexcept
Return a new array of given shape and type, filled with ones.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ones.html inNumRows inNumCols NdArray
References full.
NdArray< dtype > nc::ones(const Shape &inShape) noexcept
Return a new array of given shape and type, filled with ones.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ones.html inShape NdArray
References full.
NdArray< dtype > nc::ones_like(const NdArray< dtype > &inArray) noexcept
Return a new array of given shape and type, filled with ones.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ones_like.html inArray NdArray
References nc::NdArray< dtype >::ones.
NdArray< dtype > nc::pad(const NdArray< dtype > &inArray, uint16 inPadWidth, dtype inPadValue)
Pads an array.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.pad.html inArray inPadWidth inPadValue NdArray
References nc::NdArray< dtype >::shape, nc::Shape::rows, nc::Shape::cols, nc::NdArray< dtype >::fill, nc::NdArray< dtype >::put.
NdArray< dtype > nc::partition(const NdArray< dtype > &inArray, uint32 inKth, Axis inAxis=Axis::NONE)
Rearranges the elements in the array in such a way that value of the element in kth position is in the position it would be in a sorted array. All elements smaller than the kth element are moved before this element and all equal or greater are moved behind it. The ordering of the elements in the two partitions is undefined.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.partition.html inArray inKth kth element inAxis (Optional, default NONE) NdArray
References nc::NdArray< dtype >::partition.
NdArray< dtype > nc::percentile(const NdArray< dtype > &inArray, double inPercentile, Axis inAxis=Axis::NONE, const std::string &inInterpMethod="linear")
Compute the qth percentile of the data along the specified axis.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.percentile.html inArray inPercentile percentile must be in the range [0, 100] inAxis (Optional, default NONE) inInterpMethod (Optional) interpolation method linear: i + (j - i) * fraction, where fraction is the fractional part of the index surrounded by i and j. lower : i. higher : j. nearest : i or j, whichever is nearest. midpoint : (i + j) / 2. NdArray
References nc::utils::essentiallyEqual, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend, floor, nc::NdArray< dtype >::size, sort, nc::NdArray< dtype >::begin, nc::NdArray< dtype >::end, nc::NdArray< dtype >::shape, nc::Shape::rows, nc::NdArray< dtype >::transpose.
dtype nc::power(dtype inValue, uint8 inExponent) noexcept
Raises the elements of the array to the input integer powerNumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.power.html inValue inExponent value raised to the power
References power.
Referenced by nc::Poly1d< dtype >::str, nc::Poly1d< dtype >::operator(), nc::Poly1d< dtype >::operator^=.
NdArray< dtype > nc::power(const NdArray< dtype > &inArray, uint8 inExponent) noexcept
Raises the elements of the array to the input integer powerNumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.power.html inArray inExponent NdArray
References power.
NdArray< dtype > nc::power(const NdArray< dtype > &inArray, const NdArray< uint8 > &inExponents)
Raises the elements of the array to the input integer powersNumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.power.html inArray inExponents NdArray
References nc::NdArray< dtype >::shape, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend.
Referenced by power.
double nc::powerf(dtype inValue, double inExponent) noexcept
Raises the elements of the array to the input floating point powerNumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.power.html inValue inExponent value raised to the power
References powerf.
NdArray< double > nc::powerf(const NdArray< dtype > &inArray, double inExponent) noexcept
Raises the elements of the array to the input floating point powerNumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.power.html inArray inExponent NdArray
References powerf.
NdArray< double > nc::powerf(const NdArray< dtype > &inArray, const NdArray< double > &inExponents)
Raises the elements of the array to the input floating point powersNumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.power.html inArray inExponents NdArray
References nc::NdArray< dtype >::shape, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend.
Referenced by powerf.
void nc::print(const NdArray< dtype > &inArray) noexcept
Prints the array to the console. inArray None
NdArray< dtype > nc::prod(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Return the product of array elements over a given axis.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.prod.html inArray inAxis (Optional, default NONE) NdArray
Referenced by nanprod.
NdArray< dtype > nc::ptp(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Range of values (maximum - minimum) along an axis.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.ptp.html inArray inAxis (Optional, default NONE) NdArray
NdArray< dtype > & nc::put(NdArray< dtype > &inArray, const NdArray< uint32 > &inIndices, const NdArray< dtype > &inValues)
Replaces specified elements of an array with given values. The indexing works on the flattened target arrayNumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.put.html inArray inIndices inValues NdArray
References nc::NdArray< dtype >::put.
NdArray< dtype > & nc::putmask(NdArray< dtype > &inArray, const NdArray< bool > &inMask, dtype inValue)
Changes elements of an array based on conditional and input values.Sets a.flat[n] = values[n] for each n where mask.flat[n] == True.If values is not the same size as a and mask then it will repeat.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.putmask.html inArray inMask inValue NdArray
References nc::NdArray< dtype >::putMask.
NdArray< dtype > & nc::putmask(NdArray< dtype > &inArray, const NdArray< bool > &inMask, const NdArray< dtype > &inValues)
Changes elements of an array based on conditional and input values.Sets a.flat[n] = values[n] for each n where mask.flat[n] == True.If values is not the same size as a and mask then it will repeat.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.putmask.html inArray inMask inValues NdArray
References nc::NdArray< dtype >::putMask.
NdArray<dtype> nc::pybind2nc(pybind11::array_t< dtype, pybind11::array::c_style > &numpyArray)
converts a numpy array to a numcpp NdArray using pybind bindings Python will still own the underlying data. numpyArray NdArray<dtype>
References size.
double nc::rad2deg(dtype inValue) noexcept
Convert angles from radians to degrees.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.rad2deg.html inValue value
References nc::constants::pi.
Referenced by nc::coordinates::Coordinate::degreeSeperation.
NdArray< double > nc::rad2deg(const NdArray< dtype > &inArray) noexcept
Convert angles from radians to degrees.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.rad2deg.html inArray NdArray
Referenced by degrees.
double nc::radians(dtype inValue) noexcept
Convert angles from degrees to radians.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.radians.html inValue value
References deg2rad.
NdArray< double > nc::radians(const NdArray< dtype > &inArray) noexcept
Convert angles from degrees to radians.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.radians.html inArray NdArray
References deg2rad.
NdArray< double > nc::reciprocal(const NdArray< dtype > &inArray) noexcept
Return the reciprocal of the argument, element-wise.Calculates 1 / x.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.reciprocal.html inArray NdArray
double nc::remainder(dtype inValue1, dtype inValue2) noexcept
Return remainder of division.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.remainder.html inValue1 inValue2 NdArray
References remainder.
NdArray< double > nc::remainder(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2)
Return element-wise remainder of division.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.remainder.html inArray1 inArray2 NdArray
References nc::NdArray< dtype >::shape, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend.
Referenced by remainder.
NdArray< dtype > nc::repeat(const NdArray< dtype > &inArray, uint32 inNumRows, uint32 inNumCols) noexcept
Repeat elements of an array.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.repeat.html inArray inNumRows inNumCols NdArray
NdArray< dtype > nc::repeat(const NdArray< dtype > &inArray, const Shape &inRepeatShape) noexcept
Repeat elements of an array.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.repeat.html inArray inRepeatShape NdArray
NdArray< dtype > & nc::reshape(NdArray< dtype > &inArray, uint32 inNumRows, uint32 inNumCols)
Gives a new shape to an array without changing its data.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.reshape.html inArray inNumRows inNumCols NdArray
References nc::NdArray< dtype >::reshape.
NdArray< dtype > & nc::reshape(NdArray< dtype > &inArray, const Shape &inNewShape)
Gives a new shape to an array without changing its data.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.reshape.html inArray inNewShape NdArray
References nc::NdArray< dtype >::reshape.
NdArray< dtype > & nc::resizeFast(NdArray< dtype > &inArray, uint32 inNumRows, uint32 inNumCols) noexcept
Change shape and size of array in-place. All previous data of the array is lost.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.resize.html inArray inNumRows inNumCols NdArray
NdArray< dtype > & nc::resizeFast(NdArray< dtype > &inArray, const Shape &inNewShape) noexcept
Change shape and size of array in-place. All previous data of the array is lost.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.resize.html inArray inNewShape NdArray
NdArray< dtype > & nc::resizeSlow(NdArray< dtype > &inArray, uint32 inNumRows, uint32 inNumCols) noexcept
Return a new array with the specified shape. If new shape is larger than old shape then array will be padded with zeros. If new shape is smaller than the old shape then the data will be discarded.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.resize.html inArray inNumRows inNumCols NdArray
NdArray< dtype > & nc::resizeSlow(NdArray< dtype > &inArray, const Shape &inNewShape) noexcept
Return a new array with the specified shape. If new shape is larger than old shape then array will be padded with zeros. If new shape is smaller than the old shape then the data will be discarded.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.resize.html inArray inNewShape NdArray
NdArray< dtype > nc::right_shift(const NdArray< dtype > &inArray, uint8 inNumBits) noexcept
Shift the bits of an integer to the right.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.right_shift.html inArray inNumBits NdArray
dtype nc::rint(dtype inValue) noexcept
Round value to the nearest integer.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.rint.html inValue value
References rint.
NdArray< dtype > nc::rint(const NdArray< dtype > &inArray) noexcept
Round elements of the array to the nearest integer.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.rint.html inArray NdArray
Referenced by rint.
NdArray< double > nc::rms(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Compute the root mean square (RMS) along the specified axis. inArray inAxis (Optional, default NONE) NdArray
References nc::NdArray< dtype >::rms.
NdArray< dtype > nc::roll(const NdArray< dtype > &inArray, int32 inShift, Axis inAxis=Axis::NONE) noexcept
Roll array elements along a given axis.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.roll.html inArray inShift (elements to shift, positive means forward, negative means backwards) inAxis (Optional, default NONE) NdArray
References abs, nc::NdArray< dtype >::begin, nc::NdArray< dtype >::end, nc::Shape::cols, nc::Shape::rows, nc::NdArray< dtype >::transpose.
NdArray< dtype > nc::rot90(const NdArray< dtype > &inArray, uint8 inK=1) noexcept
Rotate an array by 90 degrees counter clockwise in the plane.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.rot90.html inArray inK the number of times to rotate 90 degrees NdArray
References flipud, flip, fliplr.
Referenced by nc::filter::convolve.
dtype nc::round(dtype inValue, uint8 inDecimals=0) noexcept
Round value to the given number of decimals. inValue inDecimals value
References nc::NdArray< dtype >::round.
Referenced by nc::rotations::DCM< dtype >::isValid.
NdArray< dtype > nc::round(const NdArray< dtype > &inArray, uint8 inDecimals=0) noexcept
Round an array to the given number of decimals. inArray inDecimals NdArray
NdArray< dtype > nc::row_stack(const std::initializer_list< NdArray< dtype > > &inArrayList)
Stack arrays in sequence vertically (row wise). inArrayList {list} of arrays to stack NdArray
References nc::Shape::isnull, nc::Shape::cols, nc::Shape::rows.
Referenced by concatenate, stack, vstack.
NdArray< dtype > nc::setdiff1d(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2)
Find the set difference of two arrays.Return the sorted, unique values in ar1 that are not in ar2.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.setdiff1d.html inArray1 inArray2 NdArray
References nc::NdArray< dtype >::size, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend.
Shape nc::shape(const NdArray< dtype > &inArray) noexcept
Return the shape of the array inArray Shape
Referenced by nc2Boost, nc2pybind.
int8 nc::sign(dtype inValue) noexcept
Returns an element-wise indication of the sign of a number.The sign function returns - 1 if x < 0, 0 if x == 0, 1 if x > 0. nan is returned for nan inputs.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.sign.html inValue NdArray
NdArray< int8 > nc::sign(const NdArray< dtype > &inArray) noexcept
Returns an element-wise indication of the sign of a number.The sign function returns - 1 if x < 0, 0 if x == 0, 1 if x > 0. nan is returned for nan inputs.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.sign.html inArray NdArray
bool nc::signbit(dtype inValue) noexcept
Returns element-wise True where signbit is set (less than zero).NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.signbit.html inValue NdArray
NdArray< bool > nc::signbit(const NdArray< dtype > &inArray) noexcept
Returns element-wise True where signbit is set (less than zero).NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.signbit.html inArray NdArray
double nc::sin(dtype inValue) noexcept
Trigonometric sine.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.sin.html inValue value
References sin.
Referenced by nc::rotations::Quaternion::angleAxisRotation, nc::rotations::Quaternion::slerp.
NdArray< double > nc::sin(const NdArray< dtype > &inArray) noexcept
Trigonometric sine, element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.sin.html inArray NdArray
Referenced by sin, sinc, unwrap.
double nc::sinc(dtype inValue) noexcept
Return the sinc function.The sinc function is sin(pi*x) / (pi*x).NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.sinc.html inValue value
References sin, nc::constants::pi.
NdArray< double > nc::sinc(const NdArray< dtype > &inArray) noexcept
Return the sinc function.The sinc function is sin(pi*x) / (pi*x).NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.sinc.html inArray NdArray
double nc::sinh(dtype inValue) noexcept
Hyperbolic sine.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.sinh.html inValue value
References sinh.
NdArray< double > nc::sinh(const NdArray< dtype > &inArray) noexcept
Hyperbolic sine, element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.sinh.html inArray NdArray
Referenced by sinh.
uint32 nc::size(const NdArray< dtype > &inArray) noexcept
Return the number of elements. inArray uint32 size
Referenced by pybind2nc.
NdArray< dtype > nc::sort(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Return a sorted copy of an array.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.sort.html inArray inAxis (Optional, default NONE) NdArray
References nc::NdArray< dtype >::sort.
Referenced by nc::filter::rankFilter, nc::filter::rankFilter1d, interp, nanpercentile, percentile, nc::NdArray< bool >::sort.
double nc::sqrt(dtype inValue) noexcept
Return the positive square-root of a value.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.sqrt.html inValue value
References sqrt.
Referenced by nc::linalg::SVD::SVD, nc::linalg::SVD::solve, nc::NdArray< bool >::norm, nc::NdArray< bool >::rms, nc::NdArray< bool >::stdev, nc::rotations::Quaternion::Quaternion, nc::rotations::Quaternion::fromDCM.
NdArray< double > nc::sqrt(const NdArray< dtype > &inArray) noexcept
Return the positive square-root of an array, element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.sqrt.html inArray NdArray
Referenced by nanstdev, sqrt.
dtype nc::square(dtype inValue) noexcept
Return the square of an array.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.square.html inValue value
References nc::utils::sqr.
Referenced by nc::rotations::Quaternion::Quaternion.
NdArray< dtype > nc::square(const NdArray< dtype > &inArray) noexcept
Return the square of an array, element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.square.html inArray NdArray
Referenced by nanvar.
NdArray< dtype > nc::stack(const std::initializer_list< NdArray< dtype > > &inArrayList, Axis inAxis=Axis::ROW)
Compute the variance along the specified axis.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.stack.html inArrayList {list} of arrays to stack inAxis axis to stack the input NdArrays NdArray
References row_stack, column_stack.
NdArray< double > nc::stdev(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Compute the standard deviation along the specified axis.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.std.html inArray inAxis (Optional, default NONE) NdArray
References nc::NdArray< dtype >::stdev.
Referenced by nc::NdArray< bool >::var.
NdArray< dtype > nc::sum(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Sum of array elements over a given axis.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.sum.html inArray inAxis (Optional, default NONE) NdArray
Referenced by average, nanmean, nanstdev, nansum, trapz, nc::NdArray< bool >::trace, nc::rotations::Quaternion::Quaternion.
NdArray< dtype > nc::swapaxes(const NdArray< dtype > &inArray) noexcept
Interchange two axes of an array.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.swapaxes.html inArray NdArray
double nc::tan(dtype inValue) noexcept
Compute tangent.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.tan.html inValue value
References tan.
NdArray< double > nc::tan(const NdArray< dtype > &inArray) noexcept
Compute tangent element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.tan.html inArray NdArray
Referenced by tan.
double nc::tanh(dtype inValue) noexcept
Compute hyperbolic tangent.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.tanh.html inValue value
References tanh.
NdArray< double > nc::tanh(const NdArray< dtype > &inArray) noexcept
Compute hyperbolic tangent element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.tanh.html inArray NdArray
Referenced by tanh.
NdArray< dtype > nc::tile(const NdArray< dtype > &inArray, uint32 inNumRows, uint32 inNumCols) noexcept
Construct an array by repeating A the number of times given by reps.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.tile.html inArray inNumRows inNumCols NdArray
NdArray< dtype > nc::tile(const NdArray< dtype > &inArray, const Shape &inReps) noexcept
Construct an array by repeating A the number of times given by reps.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.tile.html inArray inReps NdArray
void nc::tofile(const NdArray< dtype > &inArray, const std::string &inFilename, const std::string &inSep="")
Write array to a file as text or binary (default).. The data produced by this method can be recovered using the function fromfile(). inArray inFilename inSep (Separator between array items for text output. If (empty), a binary file is written) None
References nc::NdArray< dtype >::tofile.
std::vector< dtype > nc::toStlVector(const NdArray< dtype > &inArray) noexcept
Write flattened array to an STL vector inArray std::vector
dtype nc::trace(const NdArray< dtype > &inArray, int16 inOffset=0, Axis inAxis=Axis::ROW) noexcept
Return the sum along diagonals of the array.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.trace.html inArray inOffset (Offset from main diaganol, default = 0, negative=above, positve=below) inAxis (Optional, default ROW) NdArray
NdArray< dtype > nc::transpose(const NdArray< dtype > &inArray) noexcept
Permute the dimensions of an array.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.transpose.html inArray NdArray
Referenced by triu, nc::NdArray< bool >::sum, nc::NdArray< bool >::swapaxes.
NdArray< double > nc::trapz(const NdArray< dtype > &inArray, double dx=1.0, Axis inAxis=Axis::NONE) noexcept
Integrate along the given axis using the composite trapezoidal rule.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.trapz.html inArray dx (Optional defaults to 1.0) inAxis (Optional, default NONE) NdArray
References nc::Shape::rows, sum, nc::Shape::cols, nc::NdArray< dtype >::transpose, nc::NdArray< dtype >::shape.
NdArray< double > nc::trapz(const NdArray< dtype > &inArrayY, const NdArray< dtype > &inArrayX, Axis inAxis=Axis::NONE)
Integrate along the given axis using the composite trapezoidal rule.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.trapz.html inArrayY inArrayX inAxis (Optional, default NONE) NdArray
References nc::NdArray< dtype >::shape, nc::Shape::rows, sum, nc::Shape::cols, nc::NdArray< dtype >::transpose, nc::NdArray< dtype >::size.
NdArray< dtype > nc::tril(uint32 inN, int32 inOffset=0) noexcept
An array with ones at and below the given diagonal and zeros elsewhere. inN number of rows and cols inOffset (the sub-diagonal at and below which the array is filled. k = 0 is the main diagonal, while k < 0 is below it, and k > 0 is above. The default is 0.) NdArray
References nc::NdArray< dtype >::zeros.
NdArray< dtype > nc::tril(uint32 inN, uint32 inM, int32 inOffset=0) noexcept
An array with ones at and below the given diagonal and zeros elsewhere. inN number of rows inM number of columns inOffset (the sub-diagonal at and below which the array is filled. k = 0 is the main diagonal, while k < 0 is below it, and k > 0 is above. The default is 0.) NdArray
References nc::NdArray< dtype >::zeros.
NdArray< dtype > nc::tril(const NdArray< dtype > &inArray, int32 inOffset=0) noexcept
Lower triangle of an array.Return a copy of an array with elements above the k - th diagonal zeroed.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.tril.html inArray number of rows and cols inOffset (the sub-diagonal at and below which the array is filled. k = 0 is the main diagonal, while k < 0 is below it, and k > 0 is above. The default is 0.) NdArray
References nc::Shape::rows, nc::Shape::cols.
NdArray< dtype > nc::trim_zeros(const NdArray< dtype > &inArray, const std::string inTrim="fb")
Trim the leading and/or trailing zeros from a 1-D array or sequence.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.trim_zeros.html inArray inTrim ("f" = front, "b" = back, "fb" = front and back) NdArray
References copy, nc::NdArray< dtype >::size, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::begin.
NdArray< dtype > nc::triu(uint32 inN, int32 inOffset=0) noexcept
An array with ones at and above the given diagonal and zeros elsewhere. inN number of rows and cols inOffset (the sub-diagonal at and above which the array is filled. k = 0 is the main diagonal, while k < 0 is below it, and k > 0 is above. The default is 0.) NdArray
References transpose.
NdArray< dtype > nc::triu(uint32 inN, uint32 inM, int32 inOffset=0) noexcept
An array with ones at and above the given diagonal and zeros elsewhere. inN number of rows inM number of columns inOffset (the sub-diagonal at and above which the array is filled. k = 0 is the main diagonal, while k < 0 is below it, and k > 0 is above. The default is 0.) NdArray
References nc::NdArray< dtype >::ones.
NdArray< dtype > nc::triu(const NdArray< dtype > &inArray, int32 inOffset=0) noexcept
Upper triangle of an array.Return a copy of an array with elements below the k - th diagonal zeroed.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.triu.html inArray number of rows and cols inOffset (the sub-diagonal at and below which the array is filled. k = 0 is the main diagonal, while k < 0 is below it, and k > 0 is above. The default is 0.) NdArray
References nc::Shape::rows, nc::Shape::cols.
dtype nc::trunc(dtype inValue) noexcept
Return the truncated value of the input.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.trunc.html inValue value
References trunc.
NdArray< dtype > nc::trunc(const NdArray< dtype > &inArray) noexcept
Return the truncated value of the input, element-wise.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.trunc.html inArray NdArray
Referenced by trunc.
NdArray< dtype > nc::union1d(const NdArray< dtype > &inArray1, const NdArray< dtype > &inArray2)
Find the union of two arrays.Return the unique, sorted array of values that are in either of the two input arrays.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.union1d.html inArray1 inArray2 NdArray
References nc::NdArray< dtype >::shape, nc::NdArray< dtype >::cbegin, nc::NdArray< dtype >::cend.
NdArray< dtype > nc::unique(const NdArray< dtype > &inArray) noexcept
Find the unique elements of an array.Returns the sorted unique elements of an array.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.unique.html inArray NdArray
Referenced by deleteIndices.
dtype nc::unwrap(dtype inValue) noexcept
Unwrap by changing deltas between values to 2*pi complement. Unwraps to [-pi, pi].NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.unwrap.html inValue value
References sin, cos.
NdArray< dtype > nc::unwrap(const NdArray< dtype > &inArray) noexcept
Unwrap by changing deltas between values to 2*pi complement. Unwraps to [-pi, pi].NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.unwrap.html inArray NdArray
NdArray< double > nc::var(const NdArray< dtype > &inArray, Axis inAxis=Axis::NONE) noexcept
Compute the variance along the specified axis.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.var.html inArray inAxis (Optional, default NONE) NdArray
References nc::NdArray< dtype >::var.
boost::python::list nc::vector2list(std::vector< T > &inVector) noexcept
converts a std::vector to a boost python list inVector boost::python::list
NdArray< dtype > nc::vstack(const std::initializer_list< NdArray< dtype > > &inArrayList)
Compute the variance along the specified axis.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.vstack.html inArrayList {list} of arrays to stack NdArray
References row_stack.
NdArray< dtype > nc::where(const NdArray< bool > &inMask, const NdArray< dtype > &inA, const NdArray< dtype > &inB)
Return elements, either from x or y, depending on the input mask. The output array contains elements of x where mask is True, and elements from y elsewhere.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.where.html inMask inA inB NdArray
References nc::NdArray< dtype >::shape.
NdArray< dtype > nc::zeros(uint32 inSquareSize) noexcept
Return a new array of given shape and type, filled with zeros.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.zeros.html inSquareSize NdArray
References full.
NdArray< dtype > nc::zeros(uint32 inNumRows, uint32 inNumCols) noexcept
Return a new array of given shape and type, filled with zeros.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.zeros.html inNumRows inNumCols NdArray
References full.
NdArray< dtype > nc::zeros(const Shape &inShape) noexcept
Return a new array of given shape and type, filled with zeros.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.zeros.html inShape NdArray
References full.
NdArray< dtype > nc::zeros_like(const NdArray< dtype > &inArray) noexcept
Return a new array of given shape and type, filled with zeros.NumPy Reference: https://www.numpy.org/devdocs/reference/generated/numpy.zeros_like.html inArray NdArray
References nc::NdArray< dtype >::zeros.