nc::filter
Boundary
NdArray< dtype > nc::filter::addBoundary(const NdArray< dtype > &inImage, Boundary inBoundaryType, uint32 inKernalSize, dtype inConstantValue=0)
Wrap boundary inImage inBoundaryType inKernalSize inConstantValue (default 0) NdArray
References REFLECT, reflectBoundary, CONSTANT, constantBoundary, NEAREST, nearestBoundary, MIRROR, mirrorBoundary, WRAP, wrapBoundary.
Referenced by convolve, maximumFilter, medianFilter, minimumFilter, percentileFilter, rankFilter, uniformFilter.
NdArray< dtype > nc::filter::addBoundary1d(const NdArray< dtype > &inImage, Boundary inBoundaryType, uint32 inKernalSize, dtype inConstantValue=0)
Wrap boundary inImage inBoundaryType inKernalSize inConstantValue (default 0) NdArray
References REFLECT, reflectBoundary1d, CONSTANT, constantBoundary1d, NEAREST, nearestBoundary1d, MIRROR, mirrorBoundary1d, WRAP, wrapBoundary1d.
Referenced by convolve1d, maximumFilter1d, medianFilter1d, minumumFilter1d, percentileFilter1d, rankFilter1d, uniformFilter1d.
NdArray< dtype > nc::filter::complementaryMedianFilter(const NdArray< dtype > &inImageArray, uint32 inSize, Boundary inBoundaryType=Boundary::REFLECT, dtype inConstantValue=0)
Calculates a multidimensional complemenatry median filter. inImageArray inSize square size of the kernel to apply inBoundaryType boundary mode (default Reflect) options (reflect, constant, nearest, mirror, wrap) inConstantValue contant value if boundary = 'constant' (default 0) NdArray
References medianFilter.
NdArray< dtype > nc::filter::complementaryMedianFilter1d(const NdArray< dtype > &inImageArray, uint32 inSize, Boundary inBoundaryType=Boundary::REFLECT, dtype inConstantValue=0)
Calculate a one-dimensional complemenatry median filter. inImageArray inSize square size of the kernel to apply inBoundaryType boundary mode (default Reflect) options (reflect, constant, nearest, mirror, wrap) inConstantValue contant value if boundary = 'constant' (default 0) NdArray
References medianFilter1d.
NdArray< dtype > nc::filter::constantBoundary(const NdArray< dtype > &inImage, uint32 inBoundarySize, dtype inConstantValue=0)
Constant boundary inImage inBoundarySize inConstantValue NdArray
References nc::NdArray< dtype >::shape, nc::Shape::rows, nc::Shape::cols, nc::NdArray< dtype >::put, fillCorners.
Referenced by addBoundary.
NdArray< dtype > nc::filter::constantBoundary1d(const NdArray< dtype > &inImage, uint32 inBoundarySize, dtype inConstantValue=0)
Constant boundary1d inImage inBoundarySize inConstantValue NdArray
References nc::NdArray< dtype >::size, nc::NdArray< dtype >::put.
Referenced by addBoundary1d.
NdArray< dtype > nc::filter::convolve(const NdArray< dtype > &inImageArray, uint32 inSize, const NdArray< dtype > &inWeights, Boundary inBoundaryType=Boundary::REFLECT, dtype inConstantValue=0)
Calculates a multidimensional kernel convolution.SciPy Reference: https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.convolve.html#scipy.ndimage.convolve inImageArray inSize square size of the kernel to apply inWeights inBoundaryType boundary mode (default Reflect) options (reflect, constant, nearest, mirror, wrap) inConstantValue contant value if boundary = 'constant' (default 0) NdArray
References nc::NdArray< dtype >::size, nc::utils::sqr, addBoundary, nc::NdArray< dtype >::shape, nc::rot90, nc::Shape::rows, nc::Shape::cols, nc::NdArray< dtype >::flatten, nc::dot.
Referenced by gaussianFilter, laplace.
NdArray< dtype > nc::filter::convolve1d(const NdArray< dtype > &inImageArray, const NdArray< dtype > &inWeights, Boundary inBoundaryType=Boundary::REFLECT, dtype inConstantValue=0)
Calculates a one-dimensional kernel convolution.SciPy Reference: https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.convolve1d.html#scipy.ndimage.convolve1d inImageArray inWeights inBoundaryType boundary mode (default Reflect) options (reflect, constant, nearest, mirror, wrap) inConstantValue contant value if boundary = 'constant' (default 0) NdArray
References nc::NdArray< dtype >::size, addBoundary1d, nc::fliplr, nc::NdArray< dtype >::flatten, nc::dot.
Referenced by gaussianFilter1d.
void nc::filter::fillCorners(NdArray< dtype > &inArray, uint32 inBorderWidth)
extends the corner values inArray inBorderWidth
References nc::NdArray< dtype >::shape, nc::Shape::rows, nc::Shape::cols, nc::NdArray< dtype >::put.
Referenced by constantBoundary, nearestBoundary.
void nc::filter::fillCorners(NdArray< dtype > &inArray, uint32 inBorderWidth, dtype inFillValue)
extends the corner values inArray inBorderWidth inFillValue
References nc::NdArray< dtype >::shape, nc::Shape::rows, nc::Shape::cols, nc::NdArray< dtype >::put.
double nc::filter::gaussian(dtype inX, dtype inY, double inSigma) noexcept
samples a gaussian of mean zero and input STD sigma inX inY inSigma dtype
References nc::utils::sqr, nc::exp.
Referenced by gaussianFilter, gaussianFilter1d.
NdArray< dtype > nc::filter::gaussianFilter(const NdArray< dtype > &inImageArray, double inSigma, Boundary inBoundaryType=Boundary::REFLECT, dtype inConstantValue=0)
Calculates a multidimensional gaussian filter.SciPy Reference: https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.gaussian_filter.html#scipy.ndimage.gaussian_filter inImageArray inSigma Standard deviation for Gaussian kernel inBoundaryType boundary mode (default Reflect) options (reflect, constant, nearest, mirror, wrap) inConstantValue contant value if boundary = 'constant' (default 0) NdArray
References nc::max, nc::ceil, gaussian, nc::NdArray< dtype >::sum, nc::NdArray< dtype >::item, convolve.
NdArray< dtype > nc::filter::gaussianFilter1d(const NdArray< dtype > &inImageArray, double inSigma, Boundary inBoundaryType=Boundary::REFLECT, dtype inConstantValue=0)
Calculate a one-dimensional gaussian filter.SciPy Reference: https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.generic_filter1d.html#scipy.ndimage.generic_filter1d inImageArray inSigma Standard deviation for Gaussian kernel inBoundaryType boundary mode (default Reflect) options (reflect, constant, nearest, mirror, wrap) inConstantValue contant value if boundary = 'constant' (default 0) NdArray
References nc::max, nc::ceil, gaussian, nc::NdArray< dtype >::sum, nc::NdArray< dtype >::item, convolve1d.
NdArray< dtype > nc::filter::laplace(const NdArray< dtype > &inImageArray, Boundary inBoundaryType=Boundary::REFLECT, dtype inConstantValue=0)
Calculate the 2D laplace filter.SciPy Reference: https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.laplace.html#scipy.ndimage.laplace inImageArray inBoundaryType boundary mode (default Reflect) options (reflect, constant, nearest, mirror, wrap) inConstantValue contant value if boundary = 'constant' (default 0) NdArray
References convolve.
NdArray< dtype > nc::filter::maximumFilter(const NdArray< dtype > &inImageArray, uint32 inSize, Boundary inBoundaryType=Boundary::REFLECT, dtype inConstantValue=0)
Calculates a multidimensional maximum filter.SciPy Reference: https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.maximum_filter.html#scipy.ndimage.maximum_filter inImageArray inSize square size of the kernel to apply inBoundaryType boundary mode (default Reflect) options (reflect, constant, nearest, mirror, wrap) inConstantValue contant value if boundary = 'constant' (default 0) NdArray
References addBoundary, nc::NdArray< dtype >::shape, nc::NdArray< dtype >::max.
NdArray< dtype > nc::filter::maximumFilter1d(const NdArray< dtype > &inImageArray, uint32 inSize, Boundary inBoundaryType=Boundary::REFLECT, dtype inConstantValue=0)
Calculates a one-dimensional maximum filter.SciPy Reference: https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.maximum_filter1d.html#scipy.ndimage.maximum_filter1d inImageArray inSize linear size of the kernel to apply inBoundaryType boundary mode (default Reflect) options (reflect, constant, nearest, mirror, wrap) inConstantValue contant value if boundary = 'constant' (default 0) NdArray
References addBoundary1d, nc::NdArray< dtype >::size, nc::NdArray< dtype >::max.
NdArray< dtype > nc::filter::medianFilter(const NdArray< dtype > &inImageArray, uint32 inSize, Boundary inBoundaryType=Boundary::REFLECT, dtype inConstantValue=0)
Calculates a multidimensional median filter.SciPy Reference: https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.median_filter.html#scipy.ndimage.median_filter inImageArray inSize square size of the kernel to apply inBoundaryType boundary mode (default Reflect) options (reflect, constant, nearest, mirror, wrap) inConstantValue contant value if boundary = 'constant' (default 0) NdArray
References addBoundary, nc::NdArray< dtype >::shape, nc::NdArray< dtype >::median.
Referenced by complementaryMedianFilter.
NdArray< dtype > nc::filter::medianFilter1d(const NdArray< dtype > &inImageArray, uint32 inSize, Boundary inBoundaryType=Boundary::REFLECT, dtype inConstantValue=0)
Calculates a one-dimensional median filter.SciPy Reference: https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.median_filter.html#scipy.ndimage.median_filter inImageArray inSize linear size of the kernel to apply inBoundaryType boundary mode (default Reflect) options (reflect, constant, nearest, mirror, wrap) inConstantValue contant value if boundary = 'constant' (default 0) NdArray
References addBoundary1d, nc::NdArray< dtype >::size, nc::NdArray< dtype >::median.
Referenced by complementaryMedianFilter1d.
NdArray< dtype > nc::filter::minimumFilter(const NdArray< dtype > &inImageArray, uint32 inSize, Boundary inBoundaryType=Boundary::REFLECT, dtype inConstantValue=0)
Calculates a multidimensional minimum filter.SciPy Reference: https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.minimum_filter.html#scipy.ndimage.minimum_filter inImageArray inSize square size of the kernel to apply inBoundaryType boundary mode (default Reflect) options (reflect, constant, nearest, mirror, wrap) inConstantValue contant value if boundary = 'constant' (default 0) NdArray
References addBoundary, nc::NdArray< dtype >::shape, nc::NdArray< dtype >::min.
NdArray< dtype > nc::filter::minumumFilter1d(const NdArray< dtype > &inImageArray, uint32 inSize, Boundary inBoundaryType=Boundary::REFLECT, dtype inConstantValue=0)
Calculates a one-dimensional minumum filter.SciPy Reference: https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.minimum_filter1d.html#scipy.ndimage.minimum_filter1d inImageArray inSize linear size of the kernel to apply inBoundaryType boundary mode (default Reflect) options (reflect, constant, nearest, mirror, wrap) inConstantValue contant value if boundary = 'constant' (default 0) NdArray
References addBoundary1d, nc::NdArray< dtype >::size, nc::NdArray< dtype >::min.
NdArray< dtype > nc::filter::mirrorBoundary(const NdArray< dtype > &inImage, uint32 inBoundarySize)
Mirror boundary inImage inBoundarySize NdArray
References nc::NdArray< dtype >::shape, nc::Shape::rows, nc::Shape::cols, nc::NdArray< dtype >::put, nc::flipud.
Referenced by addBoundary.
NdArray< dtype > nc::filter::mirrorBoundary1d(const NdArray< dtype > &inImage, uint32 inBoundarySize)
Mirror boundary1d inImage inBoundarySize NdArray
References nc::NdArray< dtype >::size, nc::NdArray< dtype >::put, nc::fliplr.
Referenced by addBoundary1d.
NdArray< dtype > nc::filter::nearestBoundary(const NdArray< dtype > &inImage, uint32 inBoundarySize)
Nearest boundary inImage inBoundarySize NdArray
References nc::NdArray< dtype >::shape, nc::Shape::rows, nc::Shape::cols, nc::NdArray< dtype >::put, fillCorners.
Referenced by addBoundary.
NdArray< dtype > nc::filter::nearestBoundary1d(const NdArray< dtype > &inImage, uint32 inBoundarySize)
Nearest boundary1d inImage inBoundarySize NdArray
References nc::NdArray< dtype >::size, nc::NdArray< dtype >::put, nc::NdArray< dtype >::front, nc::NdArray< dtype >::back.
Referenced by addBoundary1d.
NdArray< dtype > nc::filter::percentileFilter(const NdArray< dtype > &inImageArray, uint32 inSize, uint8 inPercentile, Boundary inBoundaryType=Boundary::REFLECT, dtype inConstantValue=0)
Calculates a multidimensional percentile filter.SciPy Reference: https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.percentile_filter.html#scipy.ndimage.percentile_filter inImageArray inSize square size of the kernel to apply inPercentile percentile [0, 100] inBoundaryType boundary mode (default Reflect) options (reflect, constant, nearest, mirror, wrap) inConstantValue contant value if boundary = 'constant' (default 0) NdArray
References addBoundary, nc::NdArray< dtype >::shape, nc::NONE.
NdArray< dtype > nc::filter::percentileFilter1d(const NdArray< dtype > &inImageArray, uint32 inSize, uint8 inPercentile, Boundary inBoundaryType=Boundary::REFLECT, dtype inConstantValue=0)
Calculates a one-dimensional percentile filter.SciPy Reference: https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.percentile_filter.html#scipy.ndimage.percentile_filter inImageArray inSize linear size of the kernel to apply inPercentile percentile [0, 100] inBoundaryType boundary mode (default Reflect) options (reflect, constant, nearest, mirror, wrap) inConstantValue contant value if boundary = 'constant' (default 0) NdArray
References addBoundary1d, nc::NdArray< dtype >::size.
NdArray< dtype > nc::filter::rankFilter(const NdArray< dtype > &inImageArray, uint32 inSize, uint32 inRank, Boundary inBoundaryType=Boundary::REFLECT, dtype inConstantValue=0)
Calculates a multidimensional rank filter.SciPy Reference: https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.rank_filter.html#scipy.ndimage.rank_filter inImageArray inSize square size of the kernel to apply inRank ([0, inSize^2 - 1]) inBoundaryType boundary mode (default Reflect) options (reflect, constant, nearest, mirror, wrap) inConstantValue contant value if boundary = 'constant' (default 0) NdArray
References nc::utils::sqr, addBoundary, nc::NdArray< dtype >::shape, nc::sort.
NdArray< dtype > nc::filter::rankFilter1d(const NdArray< dtype > &inImageArray, uint32 inSize, uint8 inRank, Boundary inBoundaryType=Boundary::REFLECT, dtype inConstantValue=0)
Calculates a one-dimensional rank filter.SciPy Reference: https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.rank_filter.html#scipy.ndimage.rank_filter inImageArray inSize linear size of the kernel to apply inRank ([0, inSize^2 - 1]) inBoundaryType boundary mode (default Reflect) options (reflect, constant, nearest, mirror, wrap) inConstantValue contant value if boundary = 'constant' (default 0) NdArray
References addBoundary1d, nc::NdArray< dtype >::size, nc::sort.
NdArray< dtype > nc::filter::reflectBoundary(const NdArray< dtype > &inImage, uint32 inBoundarySize)
Reflects the boundaries inImage inBoundarySize NdArray
References nc::NdArray< dtype >::shape, nc::Shape::rows, nc::Shape::cols, nc::NdArray< dtype >::put, nc::flipud.
Referenced by addBoundary.
NdArray< dtype > nc::filter::reflectBoundary1d(const NdArray< dtype > &inImage, uint32 inBoundarySize)
Reflects the boundaries inImage inBoundarySize NdArray
References nc::NdArray< dtype >::size, nc::NdArray< dtype >::put, nc::fliplr.
Referenced by addBoundary1d.
NdArray< dtype > nc::filter::trimBoundary(const NdArray< dtype > &inImageWithBoundary, uint32 inSize)
trims the boundary off to make the image back to the original size inImageWithBoundary inSize NdArray
References nc::NdArray< dtype >::shape, nc::Shape::rows, nc::Shape::cols.
NdArray< dtype > nc::filter::trimBoundary1d(const NdArray< dtype > &inImageWithBoundary, uint32 inSize)
trims the boundary off to make the image back to the original size inImageWithBoundary inSize NdArray
References nc::NdArray< dtype >::size.
NdArray< dtype > nc::filter::uniformFilter(const NdArray< dtype > &inImageArray, uint32 inSize, Boundary inBoundaryType=Boundary::REFLECT, dtype inConstantValue=0)
Calculates a multidimensional uniform filter.SciPy Reference: https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.uniform_filter.html#scipy.ndimage.uniform_filter inImageArray inSize square size of the kernel to apply inBoundaryType boundary mode (default Reflect) options (reflect, constant, nearest, mirror, wrap) inConstantValue contant value if boundary = 'constant' (default 0) NdArray
References addBoundary, nc::NdArray< dtype >::shape, nc::NdArray< dtype >::mean, nc::NdArray< dtype >::item.
NdArray< dtype > nc::filter::uniformFilter1d(const NdArray< dtype > &inImageArray, uint32 inSize, Boundary inBoundaryType=Boundary::REFLECT, dtype inConstantValue=0)
Calculates a one-dimensional uniform filter.SciPy Reference: https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.uniform_filter1d.html#scipy.ndimage.uniform_filter1d inImageArray inSize linear size of the kernel to apply inBoundaryType boundary mode (default Reflect) options (reflect, constant, nearest, mirror, wrap) inConstantValue contant value if boundary = 'constant' (default 0) NdArray
References addBoundary1d, nc::NdArray< dtype >::size, nc::NdArray< dtype >::mean, nc::NdArray< dtype >::item.
NdArray< dtype > nc::filter::wrapBoundary(const NdArray< dtype > &inImage, uint32 inBoundarySize)
Wrap boundary inImage inBoundarySize NdArray
References nc::NdArray< dtype >::shape, nc::Shape::rows, nc::Shape::cols, nc::NdArray< dtype >::put.
Referenced by addBoundary.
NdArray< dtype > nc::filter::wrapBoundary1d(const NdArray< dtype > &inImage, uint32 inBoundarySize)
Wrap boundary1d inImage inBoundarySize NdArray
References nc::NdArray< dtype >::size, nc::NdArray< dtype >::put.
Referenced by addBoundary1d.