nc::utils
dtype nc::utils::cube(dtype inValue) noexcept
Cubes in input value inValue cubed value
bool nc::utils::essentiallyEqual(dtype inValue1, dtype inValue2, dtype inEpsilon=DtypeInfo< dtype >::epsilon()) noexcept
tests that 2 floating point values are "essentially equal" inValue1 inValue2 inEpsilon bool
References nc::abs.
Referenced by nc::coordinates::RA::operator==, nc::coordinates::Dec::operator==, nc::imageProcessing::generateThreshold, nc::nanpercentile, nc::percentile, nc::rotations::Quaternion::nlerp, nc::rotations::Quaternion::operator==.
double nc::utils::interp(dtype inValue1, dtype inValue2, double inPercent) noexcept
Returns the linear interpolation between two points inValue1 inValue2 inPercent linear interpolated point
std::string nc::utils::num2str(dtype inNumber) noexcept
Converts the number into a string inNumber std::string
Referenced by nc::coordinates::RA::str, nc::coordinates::Dec::str, nc::imageProcessing::Pixel< dtype >::str, nc::imageProcessing::Cluster< dtype >::str, nc::imageProcessing::Centroid< dtype >::str, nc::NdArray< bool >::at, nc::NdArray< bool >::dot, nc::NdArray< bool >::partition, nc::NdArray< bool >::reshape, nc::NdArray< bool >::str, nc::Poly1d< dtype >::Poly1d, nc::Poly1d< dtype >::str, nc::rotations::Quaternion::str, nc::Shape::str, nc::Slice::str, nc::Slice::makePositiveAndValidate.
dtype nc::utils::power(dtype inValue, uint8 inPower) noexcept
Raises the input value to an integer power inValue inPower inValue raised to inPower
Referenced by nc::NdArray< bool >::round, nc::Poly1d< dtype >::operator().
double nc::utils::powerf(dtype inValue, double inPower) noexcept
Raises the input value to a floating point power inValue inPower inValue raised to inPower
dtype nc::utils::sqr(dtype inValue) noexcept
Squares in input value inValue squared value
Referenced by nc::filter::gaussian, nc::filter::convolve, nc::filter::rankFilter, nc::nanstdev, nc::square, nc::NdArray< bool >::norm, nc::NdArray< bool >::rms, nc::NdArray< bool >::stdev, nc::rotations::Quaternion::Quaternion, nc::rotations::Quaternion::toDCM.